Repository aws/aws-cdk-cli, pull requests merged in 2025-09, with the labels that each got.

#815 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-assets-lib/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/THIRD_PARTY_LICENSES
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#821 fix: notices key in cdk.json is not respected
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/synth/cdk-synth-telemetry-with-errors.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/synth/cdk-synth-telemetry.integtest.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/notices.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/util/yargs-helpers.ts
  packages/aws-cdk/test/cli/cli-arguments.test.ts
  packages/aws-cdk/test/cli/cli.test.ts
Labels: p2, bug, effort/medium

#833 fix(cli): cdk flags --set without additional options should fail
  packages/aws-cdk/lib/commands/flag-operations.ts
  packages/aws-cdk/test/commands/flag-operations.test.ts
Labels: p2, bug

#830 chore: improve stability of tests by copying SSM Parameter Value
  packages/@aws-cdk/toolkit-lib/test/api/bootstrap/bootstrap-template.test.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
Labels: p2, pr/security-reviewed, pr/exempt-bootstrap-version

#849 chore: add close-stale-issues workflow
  .github/workflows/close-stale-issues.yml
Labels: p2

#782 fix(cloud-assembly-schema): `unconfiguredBehavesLike` contains info for multiple versions
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/version.json
Labels: p2

#851 chore: fix stale-issue-cleanup version
  .github/workflows/close-stale-issues.yml
Labels: p2

#852 chore(cli): remove deprecated AWS SDK v3 utilities in favor of Smithy equivalents
  .projenrc.ts
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2

#856 chore: fix codeowner team name
  packages/cdk-assets/.github/CODEOWNERS
Labels: p2

#855 refactor(cli): property bag for refreshStacks function
  packages/@aws-cdk/toolkit-lib/lib/api/garbage-collection/garbage-collector.ts
  packages/@aws-cdk/toolkit-lib/lib/api/garbage-collection/stack-refresh.ts
Labels: p2

#897 fix(cli-integ): sporadic failures due to external causes
  packages/@aws-cdk-testing/cli-integ/lib/integ-test.ts
Labels: p2
