Repository aws/aws-cdk-cli, pull requests merged in 2025-05, with the labels that each got.

#435 refactor(toolkit-lib): remove unnecessary bundling
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/sdk-logger.ts
  packages/@aws-cdk/toolkit-lib/lib/api/plugin/plugin.ts
  packages/@aws-cdk/toolkit-lib/package.json
  yarn.lock
Labels: p2

#438 fix(toolkit-lib): log monitor error missing from IoMessage
  packages/@aws-cdk/toolkit-lib/lib/api/logs-monitor/logs-monitor.ts
  packages/@aws-cdk/toolkit-lib/test/api/logs-monitor/logs-monitor.test.ts
Labels: p2

#429 feat(cli): new typescript projects use modern tsconfig
  packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/lib/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/tsconfig.json
Labels: p1, feature-request

#423 feat(cli-integ): calculate `maxWorkers` based on machine spec
  .github/workflows/integ.yml
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/resources/integ.jest.config.js
Labels: p2

#441 chore(cli): lint test files
  .projenrc.ts
  packages/aws-cdk/.eslintrc.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/_helpers/assembly.ts
  packages/aws-cdk/test/_helpers/fake-io-host.ts
  packages/aws-cdk/test/_helpers/jest-bufferedconsole.ts
  packages/aws-cdk/test/_helpers/jest-setup-after-env.ts
  packages/aws-cdk/test/_helpers/mock-sdk.ts
  packages/aws-cdk/test/_helpers/mock-toolkitinfo.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
  packages/aws-cdk/test/cli/cli-commands.test.ts
  packages/aws-cdk/test/cli/io-host/cli-io-host-corked.test.ts
  packages/aws-cdk/test/cli/io-host/cli-io-host.test.ts
  packages/aws-cdk/test/cli/version.test.ts
  packages/aws-cdk/test/commands/bootstrap.test.ts
  packages/aws-cdk/test/commands/diff.test.ts
  packages/aws-cdk/test/commands/list-stacks.test.ts
  packages/aws-cdk/test/commands/migrate.test.ts
  packages/aws-cdk/test/cxapp/exec.test.ts
  packages/aws-cdk/test/logging.test.ts
Labels: p2

#439 fix(integ-tests): tests need to `mv`ed before they can be run
  .github/workflows/integ.yml
  packages/@aws-cdk-testing/cli-integ/resources/integ.jest.config.js
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#445 refactor(toolkit): split notices code into separate files
  packages/@aws-cdk/toolkit-lib/lib/api/notices.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/cached-data-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/filter.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/notices.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/types.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/web-data-source.ts
  packages/@aws-cdk/toolkit-lib/test/api/environment/environment-resources.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/notices.test.ts
Labels: p2, pr/exempt-size-check

#421 feat(refactor): ability to exclude selected resources from refactoring
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/metadata-schema.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/refactor/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/cloudformation.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/exclude.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/exclude-refactor/index.ts
  packages/@aws-cdk/toolkit-lib/test/actions/refactor.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/refactoring/exclude.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/refactoring/refactoring.test.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
Labels: p2

#446 chore: also rc-bump version of the cli-integ package when testing
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/.projen/tasks.json
Labels: p2

#450 refactor(cli): make notices display autodect part of yargs
  packages/@aws-cdk/user-input-gen/lib/yargs-gen.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/util/yargs-helpers.ts
  packages/aws-cdk/test/cli/cli-arguments.test.ts
Labels: p2

#399 fix(cli): `cdk notices` ignores failures and calling cli with `--no-notices` makes an unexpected network call
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/cached-data-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/notices.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/web-data-source.ts
  packages/@aws-cdk/toolkit-lib/lib/util/index.ts
  packages/@aws-cdk/toolkit-lib/lib/util/net.ts
  packages/@aws-cdk/toolkit-lib/test/api/environment/environment-resources.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/notices.test.ts
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/pretty-print-error.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/commands/notices.test.ts
Labels: p2, bug, effort/medium

#444 fix(toolkit-lib): fromCdkApp fails if working directory is given and outdir is relative
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/source-builder.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/index.ts
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.ts
Labels: p2

#449 chore(deps): upgrade dependencies
  .github/workflows/release.yml
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#455 chore(contributing): link to `cli-integ` package readme for integ tests instructions
  CONTRIBUTING.md
Labels: p2

#437 feat(toolkit-lib): deploy prompt prints security diff and returns template diff
  packages/@aws-cdk/toolkit-lib/lib/payloads/deploy.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
Labels: p2

#456 chore: also write logs if integ tests fail
  .github/workflows/integ.yml
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#454 fix(toolkit): diff prints stack name not display name
  packages/@aws-cdk/toolkit-lib/lib/api/diff/diff-formatter.ts
  packages/aws-cdk/test/commands/diff.test.ts
Labels: p1, bug

#430 feat(integ-tests): add integ tests for the toolkit library
  .github/workflows/integ.yml
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/.projen/deps.json
  packages/@aws-cdk-testing/cli-integ/.projen/tasks.json
  packages/@aws-cdk-testing/cli-integ/README.md
  packages/@aws-cdk-testing/cli-integ/lib/cli/run-suite.ts
  packages/@aws-cdk-testing/cli-integ/lib/npm.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/cli-npm-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/cli-repo-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/library-globalinstall-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/library-preinstalled-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/subprocess.ts
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk-testing/cli-integ/resources/integ.jest.config.js
  packages/@aws-cdk-testing/cli-integ/tests/toolkit-lib-integ-tests/toolkit-can-cdk-deploy.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/toolkit-lib-integ-tests/toolkit-helpers.ts
  packages/@aws-cdk-testing/cli-integ/tsconfig.dev.json
  packages/@aws-cdk-testing/cli-integ/tsconfig.json
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/exec.ts
  packages/aws-cdk/lib/cxapp/exec.ts
  packages/aws-cdk/test/cxapp/exec.test.ts
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#457 chore(toolkit-lib): include @aws-cdk/cli-plugin-contract in local packaging
  packages/@aws-cdk/toolkit-lib/build-tools/package.sh
Labels: pr/exempt-integ-test, p2

#463 chore: add `toolkit-lib` to the set of locally tested packages
  .github/workflows/integ.yml
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
Labels: pr/exempt-integ-test, p2

#465 chore: off-by-one directory error
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
Labels: pr/exempt-integ-test, p2

#468 chore(toolkit-lib): reduce api-extractor noise
  .projenrc.ts
  packages/@aws-cdk/cli-lib-alpha/.gitignore
  packages/@aws-cdk/toolkit-lib/.gitattributes
  packages/@aws-cdk/toolkit-lib/.gitignore
  packages/@aws-cdk/toolkit-lib/.projen/files.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/api-extractor.json
  packages/@aws-cdk/toolkit-lib/tsdoc.json
  packages/aws-cdk/.gitignore
Labels: pr/exempt-integ-test, p2

#469 chore: unbump introduces a diff
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/package.json
Labels: pr/exempt-integ-test, p2

#474 fix(cli-integ): avoid capturing stderr when querying NPM
  packages/@aws-cdk-testing/cli-integ/lib/npm.ts
Labels: pr/exempt-integ-test, p2

#476 fix(cli-integ): error removing symlinked library
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/library-globalinstall-source.ts
Labels: pr/exempt-integ-test, p2

#459 chore: update pull-request-lint to include scope matching
  .github/workflows/pull-request-lint.yml
  .projenrc.ts
Labels: pr/exempt-integ-test, p2

#480 chore: fix amplify integ test
  .github/workflows/integ.yml
  .projenrc.ts
Labels: pr/exempt-integ-test, p2

#417 feat(cli): configurable timeout for ECS hotswap operation
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cdk-hotswap-deployment-for-ecs-service-detects-failed-deployment-and-errors.integtest.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/hotswap/common.ts
  packages/@aws-cdk/toolkit-lib/lib/api/hotswap/ecs-services.ts
  packages/@aws-cdk/toolkit-lib/test/api/hotswap/ecs-services-hotswap-deployments.test.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-configuration.ts
  packages/aws-cdk/lib/cli/user-input.ts
  packages/aws-cdk/test/cli/user-config.test.ts
Labels: p2

#478 fix(cloudformation-diff): `@aws-sdk/client-cloudformation` should be a peer dependency
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/.projen/tasks.json
  packages/@aws-cdk/cli-lib-alpha/.projen/tasks.json
  packages/@aws-cdk/cli-plugin-contract/.projen/tasks.json
  packages/@aws-cdk/cloud-assembly-schema/.projen/tasks.json
  packages/@aws-cdk/cloudformation-diff/.projen/deps.json
  packages/@aws-cdk/cloudformation-diff/.projen/tasks.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/aws-cdk/.projen/tasks.json
  packages/cdk-assets/.projen/tasks.json
  packages/cdk/.projen/tasks.json
  yarn.lock
Labels: p2

#467 refactor(toolkit-lib): remove duplicate SdkLogger and use copy of interface
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/awscli-compatible.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk-logger.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk-provider.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/tracing.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/sdk-logger.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/api/aws-auth/sdk-logger.test.ts
  packages/aws-cdk/lib/cli/cli.ts
Labels: p2

#470 refactor(toolkit-lib): use credential types from `@aws-cdk/cli-plugin-contract` instead of `@smithy/types`
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/.projen/deps.json
  packages/@aws-cdk-testing/cli-integ/.projen/tasks.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/build-tools/package.sh
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/awscli-compatible.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/credential-plugins.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/provider-caching.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk-provider.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/types.ts
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/test/_helpers/mock-sdk.ts
  packages/@aws-cdk/toolkit-lib/test/tsconfig.json
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/@aws-cdk/toolkit-lib/tsconfig.json
  packages/aws-cdk/test/_helpers/mock-sdk.ts
  packages/cdk-assets/.projen/deps.json
  packages/cdk-assets/.projen/tasks.json
  packages/cdk-assets/package.json
  yarn.lock
Labels: p2

#477 feat: generate stack definitions for refactoring
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/execution.ts
  packages/@aws-cdk/toolkit-lib/test/api/refactoring/refactoring.test.ts
Labels: p2

#482 chore(toolkit-lib): use `isolatedModules` from tsconfig instead of `ts-jest`
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/jest.config.json
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/index.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/deploy.ts
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/@aws-cdk/toolkit-lib/tsconfig.json
Labels: p2

#472 chore: require type imports in published packages to be from declared dependencies
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/.eslintrc.json
  packages/@aws-cdk/cli-lib-alpha/.eslintrc.json
  packages/@aws-cdk/cli-plugin-contract/.eslintrc.json
  packages/@aws-cdk/cloud-assembly-schema/.eslintrc.json
  packages/@aws-cdk/cloudformation-diff/.eslintrc.json
  packages/@aws-cdk/integ-runner/.eslintrc.json
  packages/@aws-cdk/toolkit-lib/.eslintrc.json
  packages/aws-cdk/.eslintrc.json
  packages/aws-cdk/lib/commands/migrate.ts
  packages/cdk-assets/.eslintrc.json
  packages/cdk/.eslintrc.json
  projenrc/eslint/index.ts
Labels: p2

#483 chore: log test durations to Markdown table
  .github/workflows/integ.yml
  packages/@aws-cdk-testing/cli-integ/lib/integ-test.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-aws.ts
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#489 chore(toolkit-lib): resolve API Extractor warnings and improve documentation
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/api-extractor.json
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/plugin/plugin.ts
  packages/@aws-cdk/toolkit-lib/tsdoc.json
Labels: p2

#488 chore(toolkit-lib): silence expected error in api-extractor config
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
Labels: p2

#490 fix: prevent coverage threshold failures in CI
  .github/workflows/codecov.yml
  projenrc/codecov.ts
Labels: pr/exempt-integ-test, p2

#491 chore: add npm cache to setup-node in integ workflow
  .github/workflows/integ.yml
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#460 feat(cli): use explicit mapping when provided by the user
  packages/@aws-cdk/toolkit-lib/lib/actions/refactor/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/refactor.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/refactoring/refactoring.test.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
Labels: p2

#495 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/lib/recommended-feature-flags.json
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.d.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#496 chore(toolkit-lib): add caret to aws-cdk/cli-plugin-contract devDep to unblock release
  packages/@aws-cdk/toolkit-lib/package.json
Labels: pr/exempt-integ-test, p2

#498 chore(cdk-assets): remove stability warning
  packages/cdk-assets/README.md
Labels: p2

#447 feat(cli): allow change set imports resources that already exist
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/import-app/app.js
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/import-app/cdk.json
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cdk-cdk-diff--import-existing-resources-shows-import.integtest.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/cfn-api.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
  packages/aws-cdk/test/commands/diff.test.ts
Labels: p2

#502 fix(cli): gc does not delete isolated assets when rollback-buffer-days is set
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cdk-gc-deletes-unused-s3-objects-rollback.integtest.ts
  packages/@aws-cdk/toolkit-lib/lib/api/garbage-collection/garbage-collector.ts
  packages/@aws-cdk/toolkit-lib/test/api/garbage-collection/garbage-collection.test.ts
Labels: p2

#503 feat(toolkit-lib): simplify action options
  packages/@aws-cdk-testing/cli-integ/lib/npm.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/cli-npm-source.ts
  packages/@aws-cdk-testing/cli-integ/lib/package-sources/library-globalinstall-source.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/destroy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/rollback/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
Labels: p2

#499 chore: use AWS_MANAGED_KEY for integ tests
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
Labels: p2

#506 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/lib/recommended-feature-flags.json
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.d.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#504 fix(cdk-assets): indicate correct docker command that failed to execute
  packages/cdk-assets/lib/private/docker.ts
Labels: p2, bug

#507 chore(toolkit-lib): remove duplicate test helpers
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/testing/fake-io-host.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/testing/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/testing/test-io-host.ts
  packages/@aws-cdk/toolkit-lib/test/api/environment/environment-resources.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/plugin/credential-plugin.test.ts
Labels: p2

#512 chore(toolkit-lib): unify IoHost helper
  packages/@aws-cdk/toolkit-lib/lib/api/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/require-approval.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/fake-io-host.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-io-host.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/environment/environment-resources.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/notices.test.ts
Labels: p2

#508 fix(toolkit-lib): MFA token cannot be provided through IoHost
  .github/workflows/integ.yml
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/awscli-compatible.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/message-maker.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/index.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/sdk.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/types.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-io-host.ts
  packages/@aws-cdk/toolkit-lib/test/api/aws-auth/sdk-provider.test.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
Labels: p2

#514 fix(toolkit-lib): dependency constraints are too strict
  .projenrc.ts
  package.json
  packages/@aws-cdk/integ-runner/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/aws-cdk/.projen/tasks.json
  packages/cdk-assets/.projen/tasks.json
  yarn.lock
Labels: p2

#513 refactor(toolkit-lib,cli): access default messages through IoHelper
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/@aws-cdk/toolkit-lib/lib/api/diff/diff-formatter.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/io-default-messages.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/io-helper.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/cached-data-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/filter.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/notices.ts
  packages/@aws-cdk/toolkit-lib/lib/api/plugin/plugin.ts
  packages/@aws-cdk/toolkit-lib/lib/api/tree.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/api/diff/diff.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/notices.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/tree.test.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/cli/messages.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/test/logging.test.ts
Labels: p2

#509 fix(cli): allow [a] to confirm garbage collection of all asset batches
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/api/garbage-collection/garbage-collector.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/gc.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/index.ts
Labels: p2

#518 refactor(toolkit-lib): all default messages go through the IoHelper
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/credential-plugins.ts
  packages/@aws-cdk/toolkit-lib/lib/api/bootstrap/bootstrap-environment.ts
  packages/@aws-cdk/toolkit-lib/lib/api/bootstrap/deploy-bootstrap.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloudformation/template-body-parameter.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/asset-publishing.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/assets.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/cfn-api.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/checks.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/deploy-stack.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/deployments.ts
  packages/@aws-cdk/toolkit-lib/lib/api/environment/environment-access.ts
  packages/@aws-cdk/toolkit-lib/lib/api/environment/environment-resources.ts
  packages/@aws-cdk/toolkit-lib/lib/api/garbage-collection/garbage-collector.ts
  packages/@aws-cdk/toolkit-lib/lib/api/garbage-collection/progress-printer.ts
  packages/@aws-cdk/toolkit-lib/lib/api/garbage-collection/stack-refresh.ts
  packages/@aws-cdk/toolkit-lib/lib/api/hotswap/hotswap-deployments.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/io-default-messages.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/span.ts
  packages/@aws-cdk/toolkit-lib/lib/api/logs-monitor/find-cloudwatch-logs.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/web-data-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/resource-import/importer.ts
  packages/@aws-cdk/toolkit-lib/lib/api/resource-import/migrator.ts
  packages/@aws-cdk/toolkit-lib/lib/api/toolkit-info.ts
  packages/@aws-cdk/toolkit-lib/lib/api/work-graph/work-graph.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
Labels: p2

#520 fix(toolkit-lib): deploy options is missing `importExistingResources` and `hotswapProperties.ecs.stabilizationTimeoutSeconds`
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/deploy-stack.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/deployment-method.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/deployments.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/hotswap/common.ts
  packages/@aws-cdk/toolkit-lib/lib/api/hotswap/ecs-services.ts
  packages/@aws-cdk/toolkit-lib/lib/api/resource-import/importer.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
Labels: p2

#521 chore: turn on DEBUG mode for integ/prepare
  .github/workflows/integ.yml
  .projenrc.ts
Labels: p2

#524 fix: property references are skipped when `DependsOn` is present (refactor)
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/digest.ts
  packages/@aws-cdk/toolkit-lib/test/api/refactoring/refactoring.test.ts
Labels: p2

#527 chore: update projen to add more logging during release bump
  package.json
  yarn.lock
Labels: p2

#519 refactor(cli): hotswap is now a deployment method
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
Labels: p2

#531 refactor(toolkit-lib): remove shared-private.ts and update references
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/types.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/stack-assembly.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-private.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit-lib/test/actions/bootstrap.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/refactor.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/deployments/cloudformation-deployments.test.ts
  packages/@aws-cdk/toolkit-lib/test/toolkit/base-credentials.test.ts
  packages/@aws-cdk/toolkit-lib/test/toolkit/plugins.test.ts
Labels: p2

#536 fix(integ-testing): sporadic timeout of `test resource import with construct that requires bundling`
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/import/cdk-test-resource-import-with-construct-that-requires-bundling.integtest.ts
Labels: p2

#533 feat(toolkit-lib)!: support custom `https.Agent` for SDK requests
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/awscli-compatible.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/proxy-agent.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/types.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/package.json
Labels: p2

#539 chore(integ-runner): remove compiled files from version control
  packages/@aws-cdk/integ-runner/lib/cli.d.ts
  packages/@aws-cdk/integ-runner/lib/cli.js
  packages/@aws-cdk/integ-runner/lib/index.d.ts
  packages/@aws-cdk/integ-runner/lib/index.js
  packages/@aws-cdk/integ-runner/lib/logger.d.ts
  packages/@aws-cdk/integ-runner/lib/logger.js
  packages/@aws-cdk/integ-runner/lib/recommended-feature-flags.json
  packages/@aws-cdk/integ-runner/lib/runner/index.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/index.js
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.js
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-suite.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-suite.js
  packages/@aws-cdk/integ-runner/lib/runner/integration-tests.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/integration-tests.js
  packages/@aws-cdk/integ-runner/lib/runner/private/cloud-assembly.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/private/cloud-assembly.js
  packages/@aws-cdk/integ-runner/lib/runner/private/integ-manifest.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/private/integ-manifest.js
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.js
  packages/@aws-cdk/integ-runner/lib/runner/snapshot-test-runner.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/snapshot-test-runner.js
  packages/@aws-cdk/integ-runner/lib/utils.d.ts
  packages/@aws-cdk/integ-runner/lib/utils.js
  packages/@aws-cdk/integ-runner/lib/workers/common.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/common.js
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.js
  packages/@aws-cdk/integ-runner/lib/workers/extract/index.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/index.js
  packages/@aws-cdk/integ-runner/lib/workers/index.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/index.js
  packages/@aws-cdk/integ-runner/lib/workers/integ-snapshot-worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-snapshot-worker.js
  packages/@aws-cdk/integ-runner/lib/workers/integ-test-worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-test-worker.js
  packages/@aws-cdk/integ-runner/lib/workers/integ-watch-worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-watch-worker.js
Labels: p2, pr/exempt-size-check

#540 fix(integ-runner): correct --clean help message
  packages/@aws-cdk/integ-runner/lib/cli.ts
Labels: p2, effort/small

#538 fix(cloud-assembly-schema): add a valid example for CcApiContextQuery
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/version.json
Labels: p2

#542 feat(toolkit-lib)!: improved types for BaseCredentials
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/api-extractor.json
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/awscli-compatible.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/base-credentials.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk-provider.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/types.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/io-host.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/io-helper.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/test/api/aws-auth/sdk-provider.test.ts
  packages/@aws-cdk/toolkit-lib/test/toolkit/base-credentials.test.ts
  packages/@aws-cdk/toolkit-lib/typedoc.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/legacy-aws-auth.ts
Labels: p2

#553 feat(toolkit-lib): General Availability of the AWS CDK Toolkit Library
  .projenrc.ts
  README.md
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/README.md
  packages/@aws-cdk/toolkit-lib/assets/.gitkeep
  packages/@aws-cdk/toolkit-lib/assets/toolkit--lib-developer_preview-important.svg
Labels: pr/exempt-integ-test, p2
