Repository aws/aws-cdk-cli, pull requests merged in 2025-07, with the labels that each got.

#680 chore(cli): diff tests should not depend on message order
  packages/aws-cdk/test/commands/diff.test.ts
Labels: pr/exempt-integ-test, p2

#682 chore(cli): cli type registry json
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/scripts/user-input-gen.ts
Labels: p2

#684 chore: make the environment deterministic for test stack
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-bucket/index.ts
Labels: p2

#685 fix(integ-runner): snapshots involving AZs are different if `enableLookups: false`
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
Labels: p2

#687 chore: `cdk-assets` did not release
  .projenrc.ts
  packages/@aws-cdk/cdk-assets-lib/.projen/tasks.json
  packages/cdk-assets/.projen/tasks.json
Labels: pr/exempt-integ-test, p2

#692 fix(integ-runner): fail with correct error when integ manifest exists but cannot be loaded
  packages/@aws-cdk/cloud-assembly-schema/lib/integ-tests/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/projenrc/versioning.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/integ.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/version.json
  packages/@aws-cdk/integ-runner/lib/logger.ts
  packages/@aws-cdk/integ-runner/lib/runner/private/integ-manifest.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.ts
  packages/@aws-cdk/integ-runner/test/helpers.ts
  packages/@aws-cdk/integ-runner/test/runner/private/invalid-manifest.test.ts
  packages/@aws-cdk/integ-runner/test/runner/runner-base-manifest-errors.test.ts
  packages/@aws-cdk/integ-runner/test/runner/snapshot-test-runner.test.ts
  packages/@aws-cdk/integ-runner/test/test-data/invalid-integ-manifest/integ.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets-diff.js.snapshot/asset.fec1c56a3f23d9d27f58815e0c34c810cc02f431ac63a078f9b5d2aa44cc3509/index.js
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets-diff.js.snapshot/cdk.out
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets-diff.js.snapshot/manifest.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets-diff.js.snapshot/test-stack.template.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets-diff.js.snapshot/tree.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets.js.snapshot/asset.be270bbdebe0851c887569796e3997437cca54ce86893ed94788500448e92824/index.js
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets.js.snapshot/cdk.out
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets.js.snapshot/manifest.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets.js.snapshot/test-stack.assets.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets.js.snapshot/test-stack.template.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.legacy-with-snapshot-assets.js.snapshot/tree.json
  packages/@aws-cdk/integ-runner/test/test-data/xxxxx.test-with-snapshot-assets-diff.js.snapshot/integ.json
Labels: p2

#693 fix: upgrade to jsii & typescript 5.8
  .projen/deps.json
  .projenrc.ts
  package.json
  packages/@aws-cdk-testing/cli-integ/.projen/deps.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-assets-lib/.projen/deps.json
  packages/@aws-cdk/cdk-assets-lib/package.json
  packages/@aws-cdk/cdk-cli-wrapper/.projen/deps.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/.projen/deps.json
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/.projen/deps.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/.projen/deps.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/.projen/deps.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/.projen/deps.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/.projen/deps.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/.projen/deps.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/commands/list-stacks.test.ts
  packages/cdk-assets/.projen/deps.json
  packages/cdk-assets/package.json
  packages/cdk/.projen/deps.json
  packages/cdk/package.json
  yarn.lock
Labels: p2

#703 refactor(cli): use IoHost in CdkToolkit
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/test/_helpers/assembly.ts
  packages/aws-cdk/test/_helpers/io-host.ts
  packages/aws-cdk/test/_helpers/promises.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
  packages/aws-cdk/test/commands/telemetry.test.ts
Labels: p2

#705 refactor(cli): use IoHost for context, docs and doctor commands
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/lib/commands/docs.ts
  packages/aws-cdk/lib/commands/doctor.ts
  packages/aws-cdk/test/cli/cli-commands.test.ts
  packages/aws-cdk/test/commands/cdk-docs.test.ts
  packages/aws-cdk/test/commands/cdk-doctor.test.ts
  packages/aws-cdk/test/commands/context-command.test.ts
Labels: p2

#706 refactor(cli): use IoHost in version and platform-warnings
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/platform-warnings.ts
  packages/aws-cdk/lib/cli/version.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/lib/commands/doctor.ts
  packages/aws-cdk/test/cli/version.test.ts
Labels: p2

#695 refactor(cli): use IoHost in CLI `Configuration`
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/user-configuration.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/test/_helpers/assembly.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
  packages/aws-cdk/test/cli/cli.test.ts
  packages/aws-cdk/test/cli/configuration.test.ts
  packages/aws-cdk/test/cli/io-host/cli-io-host-corked.test.ts
  packages/aws-cdk/test/cli/user-config.test.ts
  packages/aws-cdk/test/cli/user-context.test.ts
  packages/aws-cdk/test/commands/context-command.test.ts
  packages/aws-cdk/test/commands/diff.test.ts
  packages/aws-cdk/test/commands/drift.test.ts
  packages/aws-cdk/test/commands/list-stacks.test.ts
  packages/aws-cdk/test/commands/telemetry.test.ts
  packages/aws-cdk/test/cxapp/cloud-assembly.test.ts
  packages/aws-cdk/test/cxapp/cloud-executable.test.ts
  packages/aws-cdk/test/cxapp/exec.test.ts
  packages/aws-cdk/test/logging.test.ts
Labels: p2

#709 refactor(cli): split version functions into those that display and those that do not
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/display-version.ts
  packages/aws-cdk/lib/cli/util/yargs-helpers.ts
  packages/aws-cdk/lib/cli/version.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/lib/commands/doctor.ts
  packages/aws-cdk/test/cli/version.test.ts
Labels: pr/exempt-integ-test, p2

#699 feat: "cdk flags" command reports active and missing feature flags (unstable)
  .projenrc.ts
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/lib/api/io/toolkit-action.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/types.ts
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/test/toolkit-flags.test.ts
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-configuration.ts
  packages/aws-cdk/lib/cli/user-input.ts
  packages/aws-cdk/lib/commands/flags.ts
  packages/aws-cdk/lib/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/cli/cli-arguments.test.ts
  packages/aws-cdk/test/commands/flags.test.ts
  packages/cdk-assets/THIRD_PARTY_LICENSES
  yarn.lock
Labels: p2

#708 feat: `diff` shows moved resources
  packages/@aws-cdk/cloudformation-diff/lib/diff/types.ts
  packages/@aws-cdk/cloudformation-diff/lib/format.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/refactor/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/diff/diff-formatter.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/cloudformation.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/context.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/index.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/diff/diff.test.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
Labels: p2

#716 fix(integ-runner): assembly execution errors don't provide meaningful information
  packages/@aws-cdk/integ-runner/lib/workers/common.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/exec.ts
Labels: p2

#717 fix(integ-runner): error when running the update workflow with toolkit-lib engine
  packages/@aws-cdk/integ-runner/lib/engines/toolkit-lib.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/test/engines/toolkit-lib-snapshot-path.test.ts
Labels: p1, bug

#712 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-assets-lib/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/THIRD_PARTY_LICENSES
  packages/cdk-assets/package.json
  yarn.lock
Labels: auto-approve, p2

#725 fix(integ-runner): snapshot errors don't provide meaningful information
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.ts
Labels: p2

#728 chore: use a private package name in build-standalone-zip task
  projenrc/build-standalone-zip.task.ts
Labels: p2

#631 feat(cli): send telemetry events to local file
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/synth/cdk-synth-telemetry-with-errors.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/synth/cdk-synth-telemetry.integtest.ts
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/telemetry/error.ts
  packages/aws-cdk/lib/cli/telemetry/feature-flags.ts
  packages/aws-cdk/lib/cli/telemetry/installation-id.ts
  packages/aws-cdk/lib/cli/telemetry/library-version.ts
  packages/aws-cdk/lib/cli/telemetry/messages.ts
  packages/aws-cdk/lib/cli/telemetry/sanitation.ts
  packages/aws-cdk/lib/cli/telemetry/schema.ts
  packages/aws-cdk/lib/cli/telemetry/session.ts
  packages/aws-cdk/lib/cli/user-input.ts
  packages/aws-cdk/lib/cli/util/ci.ts
  packages/aws-cdk/lib/cli/util/yargs-helpers.ts
  packages/aws-cdk/lib/cxapp/cloud-executable.ts
  packages/aws-cdk/test/cli/io-host/cli-io-host.test.ts
  packages/aws-cdk/test/cli/telemetry/endpoint-sink.test.ts
  packages/aws-cdk/test/cli/telemetry/error.test.ts
  packages/aws-cdk/test/cli/telemetry/file-sink.test.ts
  packages/aws-cdk/test/cli/telemetry/installation-id.test.ts
  packages/aws-cdk/test/cli/telemetry/io-host-sink.test.ts
  packages/aws-cdk/test/cli/telemetry/library-version.test.ts
  packages/aws-cdk/test/cli/telemetry/sanitation.test.ts
  packages/aws-cdk/test/cli/telemetry/session.test.ts
Labels: p2

#731 fix(cli): running `--telemetry-file` without the `--unstable` option creates a telemetry file
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli-telemetry/cdk-cli-telemetry-send-to-file-unstable.integtest.ts
  packages/aws-cdk/lib/cli/cli.ts
Labels: p2

#718 feat(cli): `--no-version-reporting` equals `--no-telemetry` for cli telemetry and library metadata exclusion
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/telemetry/collect-telemetry.ts
  packages/aws-cdk/lib/cli/user-input.ts
  packages/aws-cdk/lib/cli/version.ts
  packages/aws-cdk/test/cli/telemetry/collect-telemetry.test.ts
Labels: p2

#711 chore(cli): allow valid enum values in telemetry data
  packages/aws-cdk/lib/cli/telemetry/sanitation.ts
  packages/aws-cdk/test/cli/telemetry/sanitation.test.ts
Labels: p2

#698 feat(cli): telemetry event `deploy`
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/deploy/cdk-deploy-telemetry.integtest.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/synth/cdk-synth-telemetry.integtest.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/cli/telemetry/messages.ts
  packages/aws-cdk/lib/cli/telemetry/schema.ts
Labels: p2

#739 chore: typo in readme
  packages/aws-cdk/README.md
Labels: p2

#738 feat: modify a single feature flag configuration
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/flags.ts
  packages/@aws-cdk/toolkit-lib/package.json
  packages/aws-cdk/lib/api-private.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
  packages/aws-cdk/lib/commands/flag-operations.ts
  packages/aws-cdk/lib/commands/flags.ts
  packages/aws-cdk/test/commands/flag-operations.test.ts
  packages/aws-cdk/test/commands/flags.test.ts
  yarn.lock
Labels: p2

#742 feat: change feature flag schema to store default value
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/artifact-schema.ts
Labels: p2

#736 fix(toolkit-lib): throw AuthenticationError instead of ExpiredToken
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/sdk-provider.ts
Labels: p2
