Repository aws/aws-cdk-cli, pull requests merged in 2025-03, with the labels that each got.

#178 chore: pr labeler workflow
  .gitattributes
  .github/workflows/pr-labeler.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/issue-labeler.ts
  projenrc/pr-labeler.ts
  projenrc/util.ts
Labels: pr/exempt-integ-test

#181 chore(adc): install dependencies before publishing
  .github/workflows/release.yml
  projenrc/adc-publishing.ts
Labels: pr/exempt-integ-test

#179 chore(deps): upgrade dependencies
  .github/workflows/integ.yml
  package.json
  packages/@aws-cdk/cdk-build-tools/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve

#185 chore: change SSM timestamp name to `cli-npm`
  .github/workflows/release.yml
  projenrc/record-publishing-timestamp.ts
Labels: pr/exempt-integ-test, p2

#186 fix: don't show built-in Node lifetime warnings
  .projenrc.ts
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/list-stacks.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/test/cli/cli.test.ts
  yarn.lock
Labels: pr/exempt-integ-test, p2

#187 fix(toolkit-lib): `ToolkitError` is not exported
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit-lib/package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#190 chore: use the same typescript version everywhere
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#191 chore(toolkit-lib): fix code registry is disconnected from usage
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/io-host.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/io-message.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/action-aware.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/message-maker.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/types.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/toolkit-action.ts
  packages/@aws-cdk/toolkit-lib/CODE_REGISTRY.md
  packages/@aws-cdk/toolkit-lib/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit-lib/lib/actions/list/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/context.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/codes.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/level-priority.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/logger.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/timer.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-private.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/scripts/gen-code-registry.ts
Labels: pr/exempt-integ-test, p2

#189 chore: publish `cdk-assets` as `latest`
  .github/workflows/release.yml
  .projenrc.ts
Labels: pr/exempt-integ-test, p2

#196 chore(cli): remove unused destroy options
  packages/@aws-cdk/toolkit-lib/lib/actions/destroy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api/deployments/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments/deployments.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
Labels: p2

#199 docs(toolkit-lib): add CODE_REGISTRY directly to doc site
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
Labels: pr/exempt-integ-test, p2

#198 chore: update parameters in issue-label-assign
  .github/workflows/issue-label-assign.yml
  projenrc/issue-labeler.ts
Labels: pr/exempt-integ-test, p2

#202 feat(toolkit-lib): can disable cloud assembly version and enum checks for sources
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/source-builder.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/manifest-from-the-future/cdk.out/Stack1.assets.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/manifest-from-the-future/cdk.out/Stack1.template.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/manifest-from-the-future/cdk.out/cdk.out
  packages/@aws-cdk/toolkit-lib/test/_fixtures/manifest-from-the-future/cdk.out/manifest.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/manifest-from-the-future/cdk.out/tree.json
  packages/@aws-cdk/toolkit-lib/test/_helpers/index.ts
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.ts
Labels: pr/exempt-integ-test, p2, feature-request

#204 chore: enforce `consistent-type-imports` eslint rule on modern packages
  .eslintrc.json
  .projenrc.ts
  packages/@aws-cdk/cdk-build-tools/.eslintrc.json
  packages/@aws-cdk/cdk-cli-wrapper/.eslintrc.json
  packages/@aws-cdk/cli-lib-alpha/.eslintrc.json
  packages/@aws-cdk/cli-plugin-contract/.eslintrc.json
  packages/@aws-cdk/cloud-assembly-schema/.eslintrc.json
  packages/@aws-cdk/cloudformation-diff/.eslintrc.json
  packages/@aws-cdk/node-bundle/.eslintrc.json
  packages/@aws-cdk/tmp-toolkit-helpers/.eslintrc.json
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/io-host.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/io-message.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/action-aware.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/message-maker.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/util/objects.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/util/yaml-cfn.ts
  packages/@aws-cdk/toolkit-lib/.eslintrc.json
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/private/deploy-options.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/cached-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/identity-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/stack-assembly.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/stack-selectors.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/timer.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/types.ts
  packages/@aws-cdk/toolkit-lib/lib/util/concurrency.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/index.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/jest-bufferedconsole.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-cloud-assembly-source.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-io-host.ts
  packages/@aws-cdk/toolkit-lib/test/actions/bootstrap.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/list.test.ts
  packages/@aws-cdk/user-input-gen/.eslintrc.json
  packages/@aws-cdk/yarn-cling/.eslintrc.json
  packages/aws-cdk/.eslintrc.json
  packages/cdk-assets/.eslintrc.json
  packages/cdk/.eslintrc.json
  projenrc/eslint.ts
Labels: pr/exempt-integ-test, p2

#205 chore(toolkit-lib): fixes "ambiguous redirect" error during docs publishing
  .github/workflows/release.yml
  projenrc/s3-docs-publishing.ts
Labels: pr/exempt-integ-test, p2

#206 chore(toolkit-lib): rename CODES to IO
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/sdk-logger.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/timer.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/scripts/gen-code-registry.ts
Labels: pr/exempt-integ-test, p2

#184 feat: record CLI version in manifest package
  .projenrc.ts
  packages/@aws-cdk/cloud-assembly-schema/.gitignore
  packages/@aws-cdk/cloud-assembly-schema/.npmignore
  packages/@aws-cdk/cloud-assembly-schema/.projen/tasks.json
  packages/@aws-cdk/cloud-assembly-schema/lib/manifest.ts
  packages/@aws-cdk/cloud-assembly-schema/test/manifest.test.ts
  projenrc/copy-cli-version-to-assembly.task.ts
Labels: pr/exempt-integ-test, p2

#208 chore: remove `.d.ts.map` files
  packages/@aws-cdk/toolkit-lib/test/_fixtures/external-context/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-asset/asset/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-asset/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-bucket/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-notification-arns/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-role/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_fixtures/two-empty-stacks/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_helpers/index.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-cloud-assembly-source.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-io-host.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/actions/deploy-hotswap.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/actions/destroy.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/actions/list.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/actions/rollback.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/actions/synth.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/actions/watch.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/api/io/io-message.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/toolkit/toolkit.test.d.ts.map
  packages/@aws-cdk/toolkit-lib/test/util/aws-cdk.d.ts.map
Labels: pr/exempt-integ-test, p2

#197 fix: `--force` flag does not applies to assets
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/aws-cdk/lib/api/deployments/deployments.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
  packages/cdk-assets/lib/private/asset-handler.ts
  packages/cdk-assets/lib/private/handlers/files.ts
  packages/cdk-assets/test/files.test.ts
Labels: pr/exempt-integ-test, p2

#209 refactor(cli): use IoHelper in internal APIs
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/io-helper.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/deployments/asset-publishing.ts
  packages/aws-cdk/lib/api/deployments/assets.ts
  packages/aws-cdk/lib/api/deployments/checks.ts
  packages/aws-cdk/lib/api/deployments/cloudformation.ts
  packages/aws-cdk/lib/api/deployments/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments/deployments.ts
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
  packages/aws-cdk/lib/api/environment/environment-access.ts
  packages/aws-cdk/lib/api/environment/environment-resources.ts
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/lib/api/garbage-collection/progress-printer.ts
  packages/aws-cdk/lib/api/garbage-collection/stack-refresh.ts
  packages/aws-cdk/lib/api/logs/find-cloudwatch-logs.ts
  packages/aws-cdk/lib/api/resource-import/importer.ts
  packages/aws-cdk/lib/api/resource-import/migrator.ts
  packages/aws-cdk/lib/api/stack-events/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/api/work-graph/work-graph-builder.ts
  packages/aws-cdk/lib/api/work-graph/work-graph.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/messages.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/test/_helpers/test-io-host.ts
  packages/aws-cdk/test/api/_helpers/hotswap-test-setup.ts
  packages/aws-cdk/test/api/bootstrap/bootstrap.test.ts
  packages/aws-cdk/test/api/bootstrap/bootstrap2.test.ts
  packages/aws-cdk/test/api/deployments/assets.test.ts
  packages/aws-cdk/test/api/deployments/checks.test.ts
  packages/aws-cdk/test/api/deployments/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deployments/deploy-stack.test.ts
  packages/aws-cdk/test/api/environment/environment-resources.test.ts
  packages/aws-cdk/test/api/garbage-collection/garbage-collection.test.ts
  packages/aws-cdk/test/api/resource-import/import.test.ts
  packages/aws-cdk/test/api/stack-events/stack-activity-monitor.test.ts
  packages/aws-cdk/test/api/work-graph/work-graph.test.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
Labels: pr/exempt-integ-test, p2

#210 docs(toolkit-lib): ensure all message data interfaces are documented and other improvements
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.gitignore
  packages/@aws-cdk/toolkit-lib/.npmignore
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/CODE_REGISTRY.md
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/sdk-logger.ts
  packages/@aws-cdk/toolkit-lib/lib/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/scripts/gen-code-registry.ts
  packages/@aws-cdk/toolkit-lib/test/actions/synth.test.ts
  packages/@aws-cdk/toolkit-lib/typedoc.json
Labels: pr/exempt-integ-test, p2

#215 refactor(cli): replace getters and setters with a public field
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
Labels: pr/exempt-integ-test, p2

#216 chore: remove unused dependencies
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/deps.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  packages/cdk-assets/.projen/deps.json
  packages/cdk-assets/.projen/tasks.json
  packages/cdk-assets/package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#217 refactor(cli): remove generic argument from `notify<T>()`
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/io-host.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/io-helper.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-io-host.ts
  packages/aws-cdk/lib/cli/activity-printer/base.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/test/_helpers/test-io-host.ts
Labels: pr/exempt-integ-test, p2

#220 refactor(toolkit-lib): move message definitions to shared package
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/io-message.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/bootstrap-environment-progress.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/context.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/deploy.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/destroy.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/diff.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/list.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/progress.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/rollback.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/sdk-trace.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/stack-activity.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/stack-details.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/types.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/watch.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/io-helper.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/message-maker.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/destroy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/list/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/rollback/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/watch/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/sdk-logger.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/timer.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/scripts/gen-code-registry.ts
  packages/@aws-cdk/toolkit-lib/test/toolkit/toolkit.test.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/api/deployments/asset-publishing.ts
  packages/aws-cdk/lib/api/stack-events/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/stack-events/stack-progress-monitor.ts
  packages/aws-cdk/lib/cli/activity-printer/base.ts
  packages/aws-cdk/lib/cli/activity-printer/current.ts
  packages/aws-cdk/lib/cli/activity-printer/history.ts
  packages/aws-cdk/lib/list-stacks.ts
  packages/aws-cdk/lib/logging.ts
Labels: pr/exempt-integ-test, p2

#222 chore: in tests, publish both upstream and candidate versions of schema
  .github/workflows/integ.yml
  .projenrc.ts
  package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#219 feat(toolkit-lib): emit marker messages during actions
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/deps.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloud-assembly/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloud-assembly/stack-selector.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/io-message.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/deploy.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/destroy.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/stack-activity.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/synth.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/watch.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/io-helper.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/span.ts
  packages/@aws-cdk/toolkit-lib/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/stack-selector.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/sdk-logger.ts
  packages/@aws-cdk/toolkit-lib/lib/api/io/private/timer.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/scripts/gen-code-registry.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts
  packages/aws-cdk/lib/cli/activity-printer/base.ts
Labels: pr/exempt-integ-test, p2

#218 feat(toolkit-lib): structured log monitoring events
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/logs-monitor.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api/logs/find-cloudwatch-logs.ts
  packages/aws-cdk/lib/api/logs/logs-monitor.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/test/api/logs/logs-monitor.test.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
Labels: p2

#224 fix(cdk-assets): `--profile` is ignored while publishing assets
  packages/cdk-assets/lib/aws.ts
Labels: p1, bug

#228 chore(cli): fix tests are grouped incorrectly
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
Labels: pr/exempt-integ-test, p2

#231 fix(cli): cannot set `progress` via app or user configuration
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
Labels: p2

#232 chore(toolkit-lib): fix s3 docs upload
  .github/workflows/release.yml
  projenrc/s3-docs-publishing.ts
Labels: pr/exempt-integ-test, p2

#239 docs: compatibility table for CLI/library versions
  COMPATIBILITY.md
  README.md
Labels: pr/exempt-integ-test, p2

#240 chore: remove unused packages
  .projenrc.ts
  aws-cdk-cli.code-workspace
  package.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/deps.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/tsconfig.dev.json
  packages/@aws-cdk/tmp-toolkit-helpers/tsconfig.json
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/@aws-cdk/toolkit-lib/tsconfig.json
  packages/@aws-cdk/yarn-cling/.eslintrc.js
  packages/@aws-cdk/yarn-cling/.eslintrc.json
  packages/@aws-cdk/yarn-cling/.gitattributes
  packages/@aws-cdk/yarn-cling/.gitignore
  packages/@aws-cdk/yarn-cling/.npmignore
  packages/@aws-cdk/yarn-cling/.prettierignore
  packages/@aws-cdk/yarn-cling/.prettierrc.json
  packages/@aws-cdk/yarn-cling/.projen/deps.json
  packages/@aws-cdk/yarn-cling/.projen/files.json
  packages/@aws-cdk/yarn-cling/.projen/tasks.json
  packages/@aws-cdk/yarn-cling/LICENSE
  packages/@aws-cdk/yarn-cling/NOTICE
  packages/@aws-cdk/yarn-cling/README.md
  packages/@aws-cdk/yarn-cling/bin/yarn-cling
  packages/@aws-cdk/yarn-cling/bin/yarn-cling.ts
  packages/@aws-cdk/yarn-cling/jest.config.json
  packages/@aws-cdk/yarn-cling/lib/hoisting.ts
  packages/@aws-cdk/yarn-cling/lib/index.ts
  packages/@aws-cdk/yarn-cling/lib/types.ts
  packages/@aws-cdk/yarn-cling/package.json
  packages/@aws-cdk/yarn-cling/test/cling.test.ts
  packages/@aws-cdk/yarn-cling/test/hoisting.test.ts
  packages/@aws-cdk/yarn-cling/test/test-fixture/.gitignore
  packages/@aws-cdk/yarn-cling/test/test-fixture/.no-packagejson-validator
  packages/@aws-cdk/yarn-cling/test/test-fixture/cdk/package.json
  packages/@aws-cdk/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk-lib/package.json
  packages/@aws-cdk/yarn-cling/test/test-fixture/jsii/node_modules/aws-cdk/package.json
  packages/@aws-cdk/yarn-cling/test/test-fixture/jsii/node_modules/cdk
  packages/@aws-cdk/yarn-cling/test/test-fixture/jsii/package.json
  packages/@aws-cdk/yarn-cling/test/test-fixture/yarn.lock
  packages/@aws-cdk/yarn-cling/tsconfig.dev.json
  packages/@aws-cdk/yarn-cling/tsconfig.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/_helpers/bockfs.ts
  packages/aws-cdk/test/api/aws-auth/account-cache.test.ts
  packages/aws-cdk/test/api/aws-auth/sdk-provider.test.ts
  packages/aws-cdk/test/api/cxapp/exec.test.ts
  packages/aws-cdk/tsconfig.dev.json
  packages/aws-cdk/tsconfig.json
  tsconfig.dev.json
  tsconfig.json
Labels: pr/exempt-integ-test, p2

#244 fix(cli): hotswap is reporting and running changes that don't happen
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/hotswap.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/index.ts
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/lib/api/hotswap/code-build-projects.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/hotswap/s3-bucket-deployments.ts
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
  packages/aws-cdk/test/api/hotswap/s3-bucket-hotswap-deployments.test.ts
Labels: pr/exempt-integ-test, p2

#238 fix(toolkit-lib): deployment total time includes stray output
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/span.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/api/io/span.test.ts
Labels: pr/exempt-integ-test, p2

#221 fix(cli): write notices to stderr or don't write them at all
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/io-default-messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/message-maker.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/testing/fake-io-host.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/testing/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/testing/test-io-host.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/require-approval.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/index.ts
  packages/aws-cdk/lib/cli/ci-systems.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/logging.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/lib/toolkit/cli-io-host.ts
  packages/aws-cdk/test/_helpers/test-io-host.ts
  packages/aws-cdk/test/api/_helpers/hotswap-test-setup.ts
  packages/aws-cdk/test/api/bootstrap/bootstrap.test.ts
  packages/aws-cdk/test/api/deployments/assets.test.ts
  packages/aws-cdk/test/api/deployments/checks.test.ts
  packages/aws-cdk/test/api/deployments/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deployments/deploy-stack.test.ts
  packages/aws-cdk/test/api/environment/environment-resources.test.ts
  packages/aws-cdk/test/api/garbage-collection/garbage-collection.test.ts
  packages/aws-cdk/test/api/logs/logging.test.ts
  packages/aws-cdk/test/api/logs/logs-monitor.test.ts
  packages/aws-cdk/test/api/resource-import/import.test.ts
  packages/aws-cdk/test/api/work-graph/work-graph.test.ts
  packages/aws-cdk/test/notices.test.ts
  packages/aws-cdk/test/toolkit/cli-io-host-corked.test.ts
  packages/aws-cdk/test/toolkit/cli-io-host.test.ts
Labels: p2

#250 fix(cli): hotswap output is different for different resources
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/hotswap.ts
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/lib/api/hotswap/code-build-projects.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/hotswap/s3-bucket-deployments.ts
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
Labels: p2

#252 chore: adds well-defined reason to non hotswappable resources
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/hotswap.ts
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
Labels: pr/exempt-integ-test, p2

#258 docs(toolkit-lib): await `cdk.fromAssemblyBuilder` in readme
  packages/@aws-cdk/toolkit-lib/README.md
Labels: pr/exempt-integ-test, p2

#255 refactor(cli): non hotswappable changes with structured data
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/hotswap.ts
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
Labels: pr/exempt-integ-test, p2

#260 feat(toolkit-lib): structured messages for hotswap
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/hotswap.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
Labels: pr/exempt-integ-test, p2

#246 chore: use non-caret dependency versions
  .projenrc.ts
  package.json
  packages/@aws-cdk/cdk-cli-wrapper/.projen/tasks.json
  packages/@aws-cdk/cli-lib-alpha/.projen/tasks.json
  packages/@aws-cdk/cli-plugin-contract/.projen/tasks.json
  packages/@aws-cdk/cloud-assembly-schema/.projen/tasks.json
  packages/@aws-cdk/cloudformation-diff/.projen/tasks.json
  packages/@aws-cdk/integ-runner/lib/cli.d.ts
  packages/@aws-cdk/integ-runner/lib/cli.js
  packages/@aws-cdk/integ-runner/lib/index.d.ts
  packages/@aws-cdk/integ-runner/lib/index.js
  packages/@aws-cdk/integ-runner/lib/logger.d.ts
  packages/@aws-cdk/integ-runner/lib/logger.js
  packages/@aws-cdk/integ-runner/lib/runner/index.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/index.js
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.js
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-suite.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-suite.js
  packages/@aws-cdk/integ-runner/lib/runner/integration-tests.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/integration-tests.js
  packages/@aws-cdk/integ-runner/lib/runner/private/cloud-assembly.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/private/cloud-assembly.js
  packages/@aws-cdk/integ-runner/lib/runner/private/integ-manifest.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/private/integ-manifest.js
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.js
  packages/@aws-cdk/integ-runner/lib/runner/snapshot-test-runner.d.ts
  packages/@aws-cdk/integ-runner/lib/runner/snapshot-test-runner.js
  packages/@aws-cdk/integ-runner/lib/utils.d.ts
  packages/@aws-cdk/integ-runner/lib/utils.js
  packages/@aws-cdk/integ-runner/lib/workers/common.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/common.js
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.js
  packages/@aws-cdk/integ-runner/lib/workers/extract/index.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/index.js
  packages/@aws-cdk/integ-runner/lib/workers/index.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/index.js
  packages/@aws-cdk/integ-runner/lib/workers/integ-snapshot-worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-snapshot-worker.js
  packages/@aws-cdk/integ-runner/lib/workers/integ-test-worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-test-worker.js
  packages/@aws-cdk/integ-runner/lib/workers/integ-watch-worker.d.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-watch-worker.js
  packages/@aws-cdk/node-bundle/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/user-input-gen/.projen/tasks.json
  packages/aws-cdk/.projen/tasks.json
  packages/cdk-assets/.projen/tasks.json
  packages/cdk/.projen/tasks.json
  yarn.lock
Labels: p2

#262 fix(cli): don't double up on plugin errors and don't show pointless stack trace
  .projenrc.ts
  packages/@aws-cdk/integ-runner/test/workers/integ-worker.test.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/toolkit-error.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/api/toolkit-error.test.ts
  packages/aws-cdk/lib/api/plugin/plugin.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/cli/pretty-print-error.ts
  packages/aws-cdk/test/api/plugin/plugin-host.test.ts
  packages/aws-cdk/tsconfig.dev.json
  packages/aws-cdk/tsconfig.json
Labels: pr/exempt-integ-test, p2

#268 chore: switch from 4 to 16-core runners for build workflows
  .github/workflows/build.yml
  .github/workflows/integ.yml
  .github/workflows/release.yml
  .projenrc.ts
Labels: pr/exempt-integ-test, p2

#249 feat(toolkit): add typed return to bootstrap action
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/bootstrap.test.ts
Labels: pr/exempt-integ-test, p2

#269 chore(integ-runner): fix test failing in integ workflow
  packages/@aws-cdk/integ-runner/test/runner/private/cloud-assembly.test.ts
Labels: pr/exempt-integ-test, p2

#271 chore: build with nx
  .github/workflows/build.yml
  .projen/tasks.json
  .projenrc.ts
  nx.json
  package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#273 chore: switch to isolatedModules for all tests
  .projenrc.ts
  packages/@aws-cdk/cdk-cli-wrapper/jest.config.json
  packages/@aws-cdk/cli-lib-alpha/jest.config.json
  packages/@aws-cdk/cli-plugin-contract/jest.config.json
  packages/@aws-cdk/cloud-assembly-schema/jest.config.json
  packages/@aws-cdk/cloudformation-diff/jest.config.json
  packages/@aws-cdk/integ-runner/jest.config.json
  packages/@aws-cdk/node-bundle/jest.config.json
  packages/@aws-cdk/tmp-toolkit-helpers/jest.config.json
  packages/@aws-cdk/toolkit-lib/jest.config.json
  packages/@aws-cdk/user-input-gen/jest.config.json
  packages/cdk-assets/jest.config.json
  packages/cdk/jest.config.json
Labels: pr/exempt-integ-test, p2

#267 refactor(cli): settings doesn't log anymore
  packages/aws-cdk/lib/api/settings.ts
  packages/aws-cdk/lib/cli/user-configuration.ts
Labels: p2

#266 refactor(cli): use modern messaging infrastructure
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/deployments/assets.ts
  packages/aws-cdk/lib/api/deployments/checks.ts
  packages/aws-cdk/lib/api/deployments/cloudformation.ts
  packages/aws-cdk/lib/api/deployments/deployments.ts
  packages/aws-cdk/lib/api/environment/environment-access.ts
  packages/aws-cdk/lib/api/environment/environment-resources.ts
  packages/aws-cdk/lib/api/garbage-collection/garbage-collector.ts
  packages/aws-cdk/lib/api/garbage-collection/progress-printer.ts
  packages/aws-cdk/lib/api/garbage-collection/stack-refresh.ts
  packages/aws-cdk/lib/api/resource-import/importer.ts
  packages/aws-cdk/lib/api/resource-import/migrator.ts
  packages/aws-cdk/lib/api/stack-events/stack-activity-monitor.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/api/work-graph/work-graph.ts
Labels: p2

#270 refactor(cli): new internal cloudformation api module
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/resource-metadata/index.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/cloudformation/evaluate-cloudformation-template.ts
  packages/aws-cdk/lib/api/cloudformation/index.ts
  packages/aws-cdk/lib/api/cloudformation/nested-stack-helpers.ts
  packages/aws-cdk/lib/api/cloudformation/stack-helpers.ts
  packages/aws-cdk/lib/api/cloudformation/template-body-parameter.ts
  packages/aws-cdk/lib/api/deployments/cfn-api.ts
  packages/aws-cdk/lib/api/deployments/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments/deployments.ts
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
  packages/aws-cdk/lib/api/deployments/index.ts
  packages/aws-cdk/lib/api/environment/environment-access.ts
  packages/aws-cdk/lib/api/environment/index.ts
  packages/aws-cdk/lib/api/environment/placeholders.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/lib/api/hotswap/code-build-projects.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/hotswap/s3-bucket-deployments.ts
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
  packages/aws-cdk/lib/api/logs/find-cloudwatch-logs.ts
  packages/aws-cdk/lib/api/resource-import/importer.ts
  packages/aws-cdk/lib/api/resource-import/migrator.ts
  packages/aws-cdk/lib/api/toolkit-info.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/commands/diff.ts
  packages/aws-cdk/lib/commands/migrate.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/legacy-exports-source.ts
  packages/aws-cdk/test/api/_helpers/fake-cloudformation-stack.ts
  packages/aws-cdk/test/api/_helpers/hotswap-test-setup.ts
  packages/aws-cdk/test/api/deployments/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deployments/cloudformation.test.ts
  packages/aws-cdk/test/api/deployments/hotswap-deployments.test.ts
  packages/aws-cdk/test/api/evaluate-cloudformation-template.test.ts
  packages/aws-cdk/test/api/lazy-list-stack-resources.test.ts
  packages/aws-cdk/test/api/lazy-lookup-export.test.ts
  packages/aws-cdk/test/commands/diff.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: p2

#264 refactor(cli): stack/security diff no longer prints directly to a stream
  packages/aws-cdk/lib/api/deployments/cfn-api.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/commands/diff.ts
  packages/aws-cdk/test/commands/diff.test.ts
Labels: p2

#214 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#275 fix: release integ-runner when there are changes to cloud assembly or CLI
  .projenrc.ts
  packages/@aws-cdk/integ-runner/.projen/tasks.json
Labels: pr/exempt-integ-test, p2

#276 refactor(cli): tree api with injectable logging
  packages/@aws-cdk/cli-plugin-contract/lib/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/tree.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/test/api/tree.test.ts
  packages/aws-cdk/test/notices.test.ts
Labels: p2

#274 chore: large PR checker
  .gitattributes
  .github/workflows/large-pr-checker.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/large-pr-checker.ts
Labels: pr/exempt-integ-test, p2

#277 refactor(cli): context providers use dedicated, provided messaging class
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/types.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/aws-cdk/lib/api/cxapp/cloud-executable.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/context-providers/ami.ts
  packages/aws-cdk/lib/context-providers/availability-zones.ts
  packages/aws-cdk/lib/context-providers/endpoint-service-availability-zones.ts
  packages/aws-cdk/lib/context-providers/hosted-zones.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/context-providers/keys.ts
  packages/aws-cdk/lib/context-providers/ssm-parameters.ts
  packages/aws-cdk/lib/context-providers/vpcs.ts
  packages/aws-cdk/test/context-providers/amis.test.ts
  packages/aws-cdk/test/context-providers/asymmetric-vpcs.test.ts
  packages/aws-cdk/test/context-providers/availability-zones.test.ts
  packages/aws-cdk/test/context-providers/endpoint-service-availability-zones.test.ts
  packages/aws-cdk/test/context-providers/hosted-zones.test.ts
  packages/aws-cdk/test/context-providers/keys.test.ts
  packages/aws-cdk/test/context-providers/ssm-parameters.test.ts
  packages/aws-cdk/test/context-providers/vpcs.test.ts
Labels: p2

#280 chore: update cdklabs-projen-project-types
  package.json
  packages/@aws-cdk/cdk-cli-wrapper/.projen/tasks.json
  packages/@aws-cdk/cli-lib-alpha/.projen/tasks.json
  packages/@aws-cdk/cli-plugin-contract/.projen/tasks.json
  packages/@aws-cdk/cloud-assembly-schema/.projen/tasks.json
  packages/@aws-cdk/cloudformation-diff/.projen/tasks.json
  packages/@aws-cdk/integ-runner/.projen/tasks.json
  packages/@aws-cdk/node-bundle/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/user-input-gen/.projen/tasks.json
  packages/aws-cdk/.projen/tasks.json
  packages/cdk-assets/.projen/tasks.json
  packages/cdk/.projen/tasks.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#211 feat(cli): can ignore errors and return dummy value in CloudControl API context provider
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/version.json
  packages/aws-cdk/lib/context-providers/cc-api-provider.ts
  packages/aws-cdk/test/context-providers/cc-api-provider.test.ts
Labels: pr/exempt-integ-test, p2

#281 chore: fix versions in `package.json`
  packages/@aws-cdk/integ-runner/package.json
Labels: pr/exempt-integ-test, p2

#278 chore(tmp-toolkit-helpers): `formatStackDiff` and `formatSecurityDiff` moved to tmp-toolkit-helpers
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/deps.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloudformation/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloudformation/nested-stack-templates.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloudformation/stack-helpers.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/diff.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/api/diff/diff.test.ts
  packages/@aws-cdk/tmp-toolkit-helpers/tsconfig.dev.json
  packages/@aws-cdk/tmp-toolkit-helpers/tsconfig.json
  packages/aws-cdk/lib/api/cloudformation/nested-stack-helpers.ts
  packages/aws-cdk/lib/api/cloudformation/stack-helpers.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/commands/diff.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
  yarn.lock
Labels: p2

#285 refactor(toolkit): cxapp to use moden messaging infrastructure
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/stack-assembly.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/index.ts
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/api/cxapp/cloud-executable.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/tree.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/test/_helpers/assembly.ts
  packages/aws-cdk/test/api/cxapp/exec.test.ts
  packages/aws-cdk/test/commands/diff.test.ts
Labels: p2

#283 refactor(tmp-toolkit-helpers): DiffFormatter class
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/diff-formatter.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/diff.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/api/diff/diff.test.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/commands/diff.ts
Labels: p2

#279 feat(toolkit-lib): diff
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/diff-formatter.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/diff.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/payloads/list.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/resource-import/importer.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/resource-import/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/api/diff/diff.test.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/aws-cdk/lib/api/deployments/cfn-api.ts
  packages/aws-cdk/lib/api/deployments/index.ts
  packages/aws-cdk/lib/api/resource-import/importer.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
Labels: p2
