Repository aws/aws-cdk-cli, pull requests merged in 2025-08, with the labels that each got.

#741 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-assets-lib/lib/aws-types.ts
  packages/@aws-cdk/cdk-assets-lib/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/package.json
  packages/cdk-assets/THIRD_PARTY_LICENSES
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#759 chore(cli): move sinks into their own folder
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
  packages/aws-cdk/lib/cli/telemetry/session.ts
  packages/aws-cdk/lib/cli/telemetry/sink/endpoint-sink.ts
  packages/aws-cdk/lib/cli/telemetry/sink/file-sink.ts
  packages/aws-cdk/lib/cli/telemetry/sink/io-host-sink.ts
  packages/aws-cdk/lib/cli/telemetry/sink/sink-interface.ts
  packages/aws-cdk/test/cli/telemetry/session.test.ts
  packages/aws-cdk/test/cli/telemetry/sink/endpoint-sink.test.ts
  packages/aws-cdk/test/cli/telemetry/sink/file-sink.test.ts
  packages/aws-cdk/test/cli/telemetry/sink/io-host-sink.test.ts
Labels: pr/exempt-integ-test, p2

#766 test(cli-integ): output go version in init-go integration tests
  packages/@aws-cdk-testing/cli-integ/tests/init-go/init-go.integtest.ts
Labels: p2

#768 feat(cli): update Go init templates to v1.23.0 and add post-install tidy
  packages/@aws-cdk-testing/cli-integ/tests/init-go/init-go.integtest.ts
  packages/aws-cdk/lib/commands/init/init.ts
  packages/aws-cdk/lib/init-templates/app/go/go.template.mod
  packages/aws-cdk/lib/init-templates/sample-app/go/go.template.mod
Labels: p2

#790 fix(cli): "cdk flags" message writes to `stderr` unconditionally
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/test/cli/display-flags-message.test.ts
Labels: p2

#776 feat: allow filtering `cdk flags` feature flags by substring
  packages/aws-cdk/lib/commands/flag-operations.ts
  packages/aws-cdk/test/commands/flag-operations.test.ts
Labels: p2

#793 fix(cli): acknowledge produces duplicate entries
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/test/commands/acknowledge.test.ts
Labels: p2, bug

#800 fix: skipLibCheck is not turned on for all init templates
  packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/lib/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/tsconfig.json
Labels: p2

#812 chore: allow "bootstrap" as PR scope
  .github/workflows/pull-request-lint.yml
  .projenrc.ts
Labels: p2

#779 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-assets-lib/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/package.json
  packages/cdk-assets/THIRD_PARTY_LICENSES
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#796 fix(cli): flags command shows unnecessary flags, not all table rows have vertical lines
  packages/@aws-cdk/cloudformation-diff/lib/format-table.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/commands/flag-operations.ts
  packages/aws-cdk/test/commands/flag-operations.test.ts
Labels: p2

#763 feat: add local template support with --from-path option
  packages/@aws-cdk/user-input-gen/lib/yargs-gen.ts
  packages/@aws-cdk/user-input-gen/lib/yargs-types.ts
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/convert-to-user-input.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/cli/user-input.ts
  packages/aws-cdk/lib/commands/init/init.ts
  packages/aws-cdk/test/_fixtures/init-templates/template-helpers.ts
  packages/aws-cdk/test/commands/init.test.ts
Labels: p2

#814 feat(cli): support shorthand aliases for languages
  packages/aws-cdk/README.md
  packages/aws-cdk/lib/cli/cli-config.ts
  packages/aws-cdk/lib/cli/cli-type-registry.json
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/parse-command-line-arguments.ts
  packages/aws-cdk/lib/commands/init/init.ts
  packages/aws-cdk/lib/commands/language.ts
  packages/aws-cdk/test/cli/cli.test.ts
  packages/aws-cdk/test/cli/language.test.ts
  packages/aws-cdk/test/commands/init.test.ts
Labels: p2, feature-request
