Repository aws/aws-cdk-cli, pull requests merged in 2025-04, with the labels that each got.

#251 feat(cli): CcApi context provider can be configured to fail if listing does not find a specific count of resources
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/version.json
  packages/aws-cdk/lib/context-providers/cc-api-provider.ts
  packages/aws-cdk/test/context-providers/cc-api-provider.test.ts
Labels: p2, bug

#298 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/lib/recommended-feature-flags.json
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.d.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#309 fix(toolkit): doesn't load on platforms without the Disposable API
  packages/@aws-cdk/toolkit-lib/lib/index.ts
  packages/@aws-cdk/toolkit-lib/lib/private/dispose-polyfill.ts
Labels: p2

#292 refactor(cli): aws-auth uses modern messaging infrastructure everywhere
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/testing/test-io-host.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api/aws-auth/account-cache.ts
  packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts
  packages/aws-cdk/lib/api/aws-auth/credential-plugins.ts
  packages/aws-cdk/lib/api/aws-auth/index.ts
  packages/aws-cdk/lib/api/aws-auth/proxy-agent.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-logger.ts
  packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts
  packages/aws-cdk/lib/api/aws-auth/sdk.ts
  packages/aws-cdk/lib/api/aws-auth/util.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/legacy-aws-auth.ts
  packages/aws-cdk/lib/legacy-exports-source.ts
  packages/aws-cdk/lib/legacy-exports.ts
  packages/aws-cdk/lib/notices.ts
  packages/aws-cdk/test/api/_helpers/hotswap-test-setup.ts
  packages/aws-cdk/test/api/aws-auth/account-cache.test.ts
  packages/aws-cdk/test/api/aws-auth/awscli-compatible.test.ts
  packages/aws-cdk/test/api/aws-auth/credential-plugins.test.ts
  packages/aws-cdk/test/api/aws-auth/sdk-provider.test.ts
  packages/aws-cdk/test/api/plugin/credential-plugin.test.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
  packages/aws-cdk/test/context-providers/amis.test.ts
  packages/aws-cdk/test/context-providers/availability-zones.test.ts
  packages/aws-cdk/test/context-providers/endpoint-service-availability-zones.test.ts
  packages/aws-cdk/test/context-providers/hosted-zones.test.ts
  packages/aws-cdk/test/context-providers/load-balancers.test.ts
  packages/aws-cdk/test/context-providers/security-groups.test.ts
  packages/aws-cdk/test/context-providers/ssm-parameters.test.ts
  packages/aws-cdk/test/notices.test.ts
  packages/aws-cdk/test/util/mock-sdk.ts
Labels: p2

#307 fix(toolkit-lib): remove deprecated options
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/destroy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
Labels: pr/exempt-integ-test, p2

#312 fix(toolkit-lib): remove `AsyncDisposable` from `Toolkit`
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
Labels: pr/exempt-integ-test, p2

#314 fix(toolkit-lib): remove unused extraUserAgent option from WatchOptions
  packages/@aws-cdk/toolkit-lib/lib/actions/watch/index.ts
Labels: pr/exempt-integ-test, p2

#313 fix(toolkit-lib): remove deprecated outdir option from watch
  packages/@aws-cdk/toolkit-lib/lib/actions/watch/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/watch.test.ts
Labels: pr/exempt-integ-test, p2

#306 feat(toolkit-lib): default to using a non interactive IoHost
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/deps.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/base.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/current.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/display.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/history.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/_helpers/assembly.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/_helpers/console-listener.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/activity-monitor/display.test.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/activity-monitor/history.test.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-private.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/non-interactive-io-host.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/lib/util/shell-env.ts
  packages/aws-cdk/lib/api/hotswap/index.ts
  packages/aws-cdk/lib/cli/io-host/cli-io-host.ts
Labels: pr/exempt-integ-test, p1

#315 fix(toolkit-lib): remove deprecated `DeployOptions.force` in favor of more specific options
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/private/deploy-options.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/aws-cdk/lib/api/bootstrap/bootstrap-props.ts
  packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts
  packages/aws-cdk/lib/api/deployments/deploy-stack.ts
  packages/aws-cdk/lib/api/deployments/deployments.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/test/api/deployments/cloudformation-deployments.test.ts
  packages/aws-cdk/test/api/deployments/deploy-stack.test.ts
Labels: p2

#319 chore(deps): upgrade dependencies
  .github/workflows/integ.yml
  package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/lib/recommended-feature-flags.json
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.d.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/api/cxapp/assembly-versions.ts
  packages/aws-cdk/test/api/cxapp/exec.test.ts
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#322 chore: migrate from istanbul to c8 ignore comments
  packages/@aws-cdk/tmp-toolkit-helpers/src/util/directories.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/util/type-brands.ts
  packages/aws-cdk/lib/api/logs/logs-monitor.ts
  packages/aws-cdk/lib/api/util/rwlock.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/pretty-print-error.ts
  packages/aws-cdk/lib/cli/util/npm.ts
  packages/aws-cdk/lib/cli/version.ts
  packages/aws-cdk/lib/commands/context.ts
  packages/aws-cdk/lib/commands/init/init.ts
Labels: pr/exempt-integ-test, p2

#323 refactor(cli): inject CLI version as a parameter to Notices
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/jest.config.json
  packages/@aws-cdk/tmp-toolkit-helpers/src/util/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/util/package-info.ts
  packages/aws-cdk/lib/api/environment/environment-resources.ts
  packages/aws-cdk/lib/api/notices.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/legacy-exports.ts
  packages/aws-cdk/test/api/environment/environment-resources.test.ts
  packages/aws-cdk/test/api/notices.test.ts
  packages/aws-cdk/test/cli/cli.test.ts
  packages/aws-cdk/test/context-providers/generic.test.ts
Labels: p2

#325 refactor(toolkit-lib): move payloads out of api
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/span.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/bootstrap-environment-progress.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/context.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/deploy.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/destroy.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/diff.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/hotswap.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/list.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/logs-monitor.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/progress.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/rollback.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/sdk-trace.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/stack-activity.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/stack-details.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/synth.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/types.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/watch.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/base.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/current.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/private/activity-printer/history.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-public.ts
  packages/aws-cdk/lib/api/deployments/hotswap-deployments.ts
  packages/aws-cdk/lib/api/hotswap/appsync-mapping-templates.ts
  packages/aws-cdk/lib/api/hotswap/code-build-projects.ts
  packages/aws-cdk/lib/api/hotswap/common.ts
  packages/aws-cdk/lib/api/hotswap/ecs-services.ts
  packages/aws-cdk/lib/api/hotswap/lambda-functions.ts
  packages/aws-cdk/lib/api/hotswap/s3-bucket-deployments.ts
  packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts
  packages/aws-cdk/lib/api/logs/logs-monitor.ts
Labels: pr/exempt-integ-test, p2

#324 refactor(cli): rename `logs` to `logs-monitor`
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-private.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-public.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/non-interactive-io-host.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/_helpers/test-io-host.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/aws-cdk/lib/api/cxapp/exec.ts
  packages/aws-cdk/lib/api/logs-monitor/find-cloudwatch-logs.ts
  packages/aws-cdk/lib/api/logs-monitor/index.ts
  packages/aws-cdk/lib/api/logs-monitor/logs-monitor.ts
  packages/aws-cdk/lib/api/rwlock.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/test/api/cloudformation/evaluate-cloudformation-template.test.ts
  packages/aws-cdk/test/api/cloudformation/lazy-list-stack-resources.test.ts
  packages/aws-cdk/test/api/cloudformation/lazy-lookup-export.test.ts
  packages/aws-cdk/test/api/cxapp/exec.test.ts
  packages/aws-cdk/test/api/logs-monitor/find-cloudwatch-logs.test.ts
  packages/aws-cdk/test/api/logs-monitor/logs-monitor.test.ts
  packages/aws-cdk/test/api/rwlock.test.ts
  packages/aws-cdk/test/logging.test.ts
Labels: p2

#316 chore: enable atmosphere
  .github/workflows/integ.yml
  .projenrc.ts
Labels: p2

#330 chore: update cdklabs-projen-project-types to 0.2.14 and set maxWorkers to 150
  .github/workflows/integ.yml
  .projenrc.ts
  package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#317 feat(toolkit): add a return type for `toolkit.deploy()`
  packages/@aws-cdk/cloud-assembly-schema/lib/cloud-assembly/schema.ts
  packages/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json
  packages/@aws-cdk/cloud-assembly-schema/schema/version.json
  packages/@aws-cdk/toolkit-lib/lib/toolkit/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/types.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/app.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.out/assembly-Stage/StageStack130339B27.assets.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.out/assembly-Stage/StageStack130339B27.template.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.out/assembly-Stage/cdk.out
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.out/assembly-Stage/manifest.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.out/cdk.out
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.out/manifest.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/nested-assembly/cdk.out/tree.json
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
Labels: pr/exempt-integ-test, p2

#329 refactor(toolkit): pull out interesting parts of cxapp
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloud-assembly/environment.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloud-assembly/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloud-assembly/stack-assembly.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloud-assembly/stack-collection.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/private.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/settings.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/stack-assembly.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api-private.ts
  packages/aws-cdk/lib/api/cloud-assembly.ts
  packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/api/index.ts
  packages/aws-cdk/lib/api/resource-import/migrator.ts
  packages/aws-cdk/lib/api/settings.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/commands/list-stacks.ts
  packages/aws-cdk/lib/cxapp/cloud-assembly.ts
  packages/aws-cdk/lib/cxapp/cloud-executable.ts
  packages/aws-cdk/lib/cxapp/environments.ts
  packages/aws-cdk/lib/cxapp/exec.ts
  packages/aws-cdk/lib/cxapp/index.ts
  packages/aws-cdk/lib/legacy-aws-auth.ts
  packages/aws-cdk/lib/legacy-exports-source.ts
  packages/aws-cdk/lib/legacy-exports.ts
  packages/aws-cdk/lib/legacy-types.ts
  packages/aws-cdk/test/_helpers/assembly.ts
  packages/aws-cdk/test/cxapp/assembly-versions.ts
  packages/aws-cdk/test/cxapp/cloud-assembly.test.ts
  packages/aws-cdk/test/cxapp/cloud-executable.test.ts
  packages/aws-cdk/test/cxapp/exec.test.ts
Labels: p2

#331 refactor(toolkit): move simple apis to shared helper package
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/context.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/notices.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/rwlock.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/stack-events/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/stack-events/stack-activity-monitor.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/stack-events/stack-event-poller.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/stack-events/stack-progress-monitor.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/stack-events/stack-status.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/tags.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/tree.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/work-graph/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/work-graph/work-graph-builder.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/work-graph/work-graph-types.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/work-graph/work-graph.ts
  packages/@aws-cdk/toolkit-lib/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/types.ts
  packages/@aws-cdk/toolkit-lib/test/actions/bootstrap.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy-hotswap.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/destroy.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/list.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/rollback.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/watch.test.ts
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.ts
  packages/@aws-cdk/toolkit-lib/test/toolkit/toolkit.test.ts
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/@aws-cdk/toolkit-lib/tsconfig.dts.json
  packages/aws-cdk/lib/api/context.ts
  packages/aws-cdk/lib/api/notices.ts
  packages/aws-cdk/lib/api/rwlock.ts
  packages/aws-cdk/lib/api/stack-events.ts
  packages/aws-cdk/lib/api/tags.ts
  packages/aws-cdk/lib/api/tree.ts
  packages/aws-cdk/lib/api/work-graph.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/test/api/stack-events/progress-monitor.test.ts
Labels: pr/exempt-integ-test, p2, pr/exempt-size-check

#337 refactor(toolkit): move context providers
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/ami.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/availability-zones.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/cc-api-provider.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/endpoint-service-availability-zones.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/hosted-zones.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/keys.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/load-balancers.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/security-groups.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/ssm-parameters.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/vpcs.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-private.ts
  packages/aws-cdk/lib/context-providers/ami.ts
  packages/aws-cdk/lib/context-providers/availability-zones.ts
  packages/aws-cdk/lib/context-providers/cc-api-provider.ts
  packages/aws-cdk/lib/context-providers/endpoint-service-availability-zones.ts
  packages/aws-cdk/lib/context-providers/hosted-zones.ts
  packages/aws-cdk/lib/context-providers/index.ts
  packages/aws-cdk/lib/context-providers/keys.ts
  packages/aws-cdk/lib/context-providers/load-balancers.ts
  packages/aws-cdk/lib/context-providers/security-groups.ts
  packages/aws-cdk/lib/context-providers/ssm-parameters.ts
  packages/aws-cdk/lib/context-providers/vpcs.ts
Labels: pr/exempt-integ-test, p2

#338 refactor(toolkit): move the rest
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/garbage-collection/garbage-collector.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/garbage-collection/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/garbage-collection/progress-printer.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/garbage-collection/stack-refresh.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/logs-monitor/find-cloudwatch-logs.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/logs-monitor/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/logs-monitor/logs-monitor.ts
  packages/@aws-cdk/toolkit-lib/.eslintrc.json
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/private/deploy-options.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/test/_helpers/mock-sdk.ts
  packages/@aws-cdk/toolkit-lib/test/actions/bootstrap.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/deploy.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/@aws-cdk/toolkit-lib/test/util/aws-cdk.ts
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/@aws-cdk/toolkit-lib/tsconfig.json
  packages/aws-cdk/jest.config.json
  packages/aws-cdk/lib/api/garbage-collection.ts
  packages/aws-cdk/lib/api/garbage-collection/index.ts
  packages/aws-cdk/lib/api/index.ts
  packages/aws-cdk/lib/api/logs-monitor.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/test/api/garbage-collection/garbage-collection.test.ts
  packages/aws-cdk/test/api/logs-monitor/find-cloudwatch-logs.test.ts
  packages/aws-cdk/test/cli/cli-commands.test.ts
Labels: p2

#311 chore: enable using the new toolkit from cli
  .github/workflows/release.yml
  .projenrc.ts
  package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/build-tools/build-info.sh
  packages/@aws-cdk/toolkit-lib/build-tools/bundle.mjs
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/exec.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cxapp/cloud-executable.ts
  packages/aws-cdk/package.json
  packages/aws-cdk/tsconfig.dev.json
  packages/aws-cdk/tsconfig.json
  tsconfig.dev.json
  tsconfig.json
  yarn.lock
Labels: p2

#318 feat(toolkit): add a return type for toolkit.destroy()
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/cloudformation/stack-helpers.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/deployments/deploy-stack.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/deployments/deployments.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/types.ts
  packages/@aws-cdk/toolkit-lib/test/actions/rollback.test.ts
Labels: pr/exempt-integ-test, p2

#343 chore: upgrade to alpha `jest-environment-node`
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#350 chore: switch to an explicit old version of CodeCov CLI
  .github/workflows/codecov.yml
  projenrc/codecov.ts
Labels: pr/exempt-integ-test, p2

#348 chore: update buffered console types to new jest environment
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: pr/exempt-integ-test, p2

#352 chore: enforce major version for cdk, aws-cdk, and cli-lib-alpha
  .projenrc.ts
  packages/@aws-cdk/cli-lib-alpha/.projen/tasks.json
  packages/aws-cdk/.projen/tasks.json
  packages/cdk/.projen/tasks.json
Labels: pr/exempt-integ-test, p2

#353 chore: force minor version bumps for aws-cdk package
  .projenrc.ts
  packages/aws-cdk/.projen/tasks.json
  projenrc/next-version.ts
Labels: p2

#346 chore: don't search for coverage files
  .github/workflows/codecov.yml
  projenrc/codecov.ts
Labels: pr/exempt-integ-test, p2

#342 feat: refactor (dry-run mode only)
  packages/@aws-cdk/cloudformation-diff/lib/index.ts
  packages/@aws-cdk/cloudformation-diff/lib/mappings.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/aws-auth/sdk.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/diff-formatter.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/private/messages.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/io/toolkit-action.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/refactoring/cloudformation.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/refactoring/digest.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/refactoring/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/streams.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/payloads/refactor.ts
  packages/@aws-cdk/toolkit-lib/docs/message-registry.md
  packages/@aws-cdk/toolkit-lib/lib/actions/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/refactor/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/refactor.test.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/test/_helpers/mock-sdk.ts
  packages/aws-cdk/test/api/refactoring/refactoring.test.ts
Labels: p2

#351 fix(docs): api-extractor uses 'toolkit-lib-api-model' name
  .github/workflows/release.yml
  .projenrc.ts
  projenrc/s3-docs-publishing.ts
Labels: pr/exempt-integ-test, p2

#359 chore: use `>=` for dependencies on `cloud-assembly-schema`
  .projenrc.ts
  packages/@aws-cdk/integ-runner/.projen/tasks.json
  packages/aws-cdk/.projen/tasks.json
  packages/cdk-assets/.projen/tasks.json
Labels: p2

#356 chore: retry .NET CLI mutex errors
  packages/aws-cdk/lib/commands/init/init-hooks.ts
Labels: p2

#361 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/lib/recommended-feature-flags.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#368 feat(toolkit-lib): add a return type for toolkit.diff()
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/diff/diff-formatter.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/two-different-stacks/index.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
Labels: p2

#380 chore: `@aws-cdk/toolkit-lib` is now a part of the toolkit packages
  .projenrc.ts
  packages/@aws-cdk/cli-lib-alpha/.projen/tasks.json
  packages/@aws-cdk/integ-runner/.projen/tasks.json
  packages/aws-cdk/.projen/tasks.json
  packages/cdk/.projen/tasks.json
Labels: p2

#374 chore: syntax check test files
  .projen/deps.json
  .projenrc.ts
  package.json
  packages/@aws-cdk/tmp-toolkit-helpers/.gitattributes
  packages/@aws-cdk/tmp-toolkit-helpers/.gitignore
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/files.json
  packages/@aws-cdk/tmp-toolkit-helpers/.projen/tasks.json
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/security-groups.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/_helpers/jest-bufferedconsole.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/api/diff/diff.test.ts
  packages/@aws-cdk/tmp-toolkit-helpers/test/tsconfig.json
  packages/@aws-cdk/toolkit-lib/.gitattributes
  packages/@aws-cdk/toolkit-lib/.gitignore
  packages/@aws-cdk/toolkit-lib/.projen/files.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.ts
  packages/@aws-cdk/toolkit-lib/test/tsconfig.json
  packages/aws-cdk/.gitattributes
  packages/aws-cdk/.gitignore
  packages/aws-cdk/.projen/files.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/test/_helpers/mock-sdk.ts
  packages/aws-cdk/test/api/aws-auth/sdk-logger.test.ts
  packages/aws-cdk/test/api/aws-auth/sdk-provider.test.ts
  packages/aws-cdk/test/api/cloudformation/evaluate-cloudformation-template.test.ts
  packages/aws-cdk/test/api/hotswap/appsync-mapping-templates-hotswap-deployments.test.ts
  packages/aws-cdk/test/api/plugin/plugin-host.test.ts
  packages/aws-cdk/test/api/work-graph/work-graph-builder.test.ts
  packages/aws-cdk/test/cli/cdk-toolkit.test.ts
  packages/aws-cdk/test/tsconfig.json
  packages/cdk-assets/.gitattributes
  packages/cdk-assets/.gitignore
  packages/cdk-assets/.projen/files.json
  packages/cdk-assets/.projen/tasks.json
  packages/cdk-assets/test/tsconfig.json
  projenrc/TypecheckTests.ts
  yarn.lock
Labels: pr/exempt-integ-test, p2

#381 chore(toolkit-lib): diff test fails if AWS credentials set
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
Labels: pr/exempt-integ-test, p2

#375 feat(toolkit-lib): make the plugin host configurable
  .projenrc.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/aws-auth/credential-plugins.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/aws-auth/sdk-provider.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/plugin/plugin.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/index.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/context-providers/security-groups.ts
  packages/@aws-cdk/tmp-toolkit-helpers/tsconfig.dev.json
  packages/@aws-cdk/tmp-toolkit-helpers/tsconfig.json
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-public.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-defined-env/app.js
  packages/@aws-cdk/toolkit-lib/test/_helpers/mock-sdk.ts
  packages/@aws-cdk/toolkit-lib/test/toolkit/plugins.test.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/cli/singleton-plugin-host.ts
  packages/aws-cdk/lib/cxapp/cloud-executable.ts
  packages/aws-cdk/lib/legacy-aws-auth.ts
  packages/aws-cdk/test/_helpers/mock-sdk.ts
  packages/aws-cdk/test/api/aws-auth/credential-plugins.test.ts
  packages/aws-cdk/test/api/aws-auth/sdk-provider.test.ts
  packages/aws-cdk/test/api/plugin/credential-plugin.test.ts
  packages/aws-cdk/test/api/plugin/plugin-host.test.ts
  packages/aws-cdk/test/context-providers/generic.test.ts
Labels: p2

#382 fix(toolkit-lib): errors from async builders are not caught
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/source-builder.ts
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.ts
Labels: pr/exempt-integ-test, p2

#388 feat(toolkit-lib): make base credentials configurable
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/aws-auth/awscli-compatible.ts
  packages/@aws-cdk/tmp-toolkit-helpers/src/api/aws-auth/sdk-provider.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/types.ts
  packages/@aws-cdk/toolkit-lib/lib/api/shared-private.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/stack-with-env-from-env/app.js
  packages/@aws-cdk/toolkit-lib/test/_helpers/mock-sdk.ts
  packages/@aws-cdk/toolkit-lib/test/actions/bootstrap.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/diff.test.ts
  packages/@aws-cdk/toolkit-lib/test/actions/refactor.test.ts
  packages/@aws-cdk/toolkit-lib/test/toolkit/base-credentials.test.ts
  packages/aws-cdk/lib/cli/cli.ts
  packages/aws-cdk/lib/legacy-aws-auth.ts
  packages/aws-cdk/test/_helpers/mock-sdk.ts
  packages/aws-cdk/test/api/aws-auth/awscli-compatible.test.ts
  packages/aws-cdk/test/api/aws-auth/sdk-provider.test.ts
Labels: p2

#391 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/lib/recommended-feature-flags.json
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.d.ts
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/tmp-toolkit-helpers/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  yarn.lock
Labels: auto-approve, p2

#295 fix(cli): remove unnecessary `dom` lib from default TypeScript config created with `cdk init`
  .github/workflows/codecov.yml
  .projenrc.ts
  packages/@aws-cdk/cdk-cli-wrapper/tsconfig.dev.json
  packages/@aws-cdk/cdk-cli-wrapper/tsconfig.json
  packages/@aws-cdk/cli-lib-alpha/tsconfig.dev.json
  packages/@aws-cdk/cli-plugin-contract/tsconfig.dev.json
  packages/@aws-cdk/cli-plugin-contract/tsconfig.json
  packages/@aws-cdk/cloudformation-diff/tsconfig.dev.json
  packages/@aws-cdk/cloudformation-diff/tsconfig.json
  packages/@aws-cdk/node-bundle/tsconfig.dev.json
  packages/@aws-cdk/node-bundle/tsconfig.json
  packages/@aws-cdk/user-input-gen/tsconfig.dev.json
  packages/@aws-cdk/user-input-gen/tsconfig.json
  packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/lib/typescript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/javascript/tsconfig.json
  packages/aws-cdk/lib/init-templates/sample-app/typescript/tsconfig.json
  packages/cdk-assets/tsconfig.dev.json
  packages/cdk-assets/tsconfig.json
  packages/cdk/tsconfig.dev.json
  packages/cdk/tsconfig.json
  projenrc/codecov.ts
Labels: p2, bug

#401 chore(toolkit-lib): fix typo in docs
  .github/workflows/large-pr-checker.yml
  packages/@aws-cdk/toolkit-lib/README.md
  projenrc/large-pr-checker.ts
Labels: pr/exempt-integ-test, p2

#408 chore: ignore .lock files in the PR checker
  .github/workflows/large-pr-checker.yml
  .projenrc.ts
Labels: pr/exempt-integ-test, p2

#400 feat(cli-integ): speed up image pulls by logging into ECR public
  packages/@aws-cdk-testing/cli-integ/lib/with-cdk-app.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-cli-lib.ts
  packages/@aws-cdk-testing/cli-integ/lib/with-sam.ts
Labels: p2

#415 chore: add `CdkCliIntegTests` to this repo
  .projenrc.ts
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#416 chore: log integ test output to the file system
  .github/workflows/integ.yml
  packages/@aws-cdk-testing/cli-integ/lib/integ-test.ts
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#419 feat(cli-integ): optionally print memory usage on test start/finish
  packages/@aws-cdk-testing/cli-integ/lib/integ-test.ts
Labels: p2

#433 chore: `yarn-cling` dependency is incorrectly set to `*`
  packages/@aws-cdk-testing/cli-integ/package.json
Labels: pr/exempt-integ-test, p2

#426 chore: make logs artifacts unique per matrix job
  .github/workflows/integ.yml
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#432 chore(toolkit): cleanup deps and remove unused deps
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/toolkit-lib/test/tsconfig.json
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/@aws-cdk/toolkit-lib/tsconfig.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  packages/cdk-assets/.projen/deps.json
  packages/cdk-assets/.projen/tasks.json
  packages/cdk-assets/package.json
  yarn.lock
Labels: p2

#436 chore(toolkit-lib): revert back to nock@13 for more stable tests
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/.projen/deps.json
  packages/@aws-cdk/toolkit-lib/.projen/tasks.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2

#431 chore: allow running integ tests on all branches
  .github/workflows/integ.yml
  projenrc/cdk-cli-integ-tests.ts
Labels: p2
