Repository aws/aws-cdk-cli, pull requests merged in 2025-06, with the labels that each got.

#563 fix(toolkit-lib): `refactor` feature is not marked as unstable
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/refactor.test.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
Labels: p2

#564 fix(toolkit-lib): cannot use `watch` action without explicitly providing `include` or `exclude` patterns
  packages/@aws-cdk/toolkit-lib/lib/actions/watch/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/watch/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/@aws-cdk/toolkit-lib/test/actions/watch.test.ts
Labels: p2

#569 fix(cli): update `cdk-from-cfn` to fix a number of `cdk migrate` bugs
  .projenrc.ts
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2

#581 chore: prevent api-extractor from publishing tagsForStack
  packages/@aws-cdk/toolkit-lib/lib/api/tags/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/tags/private/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/tags/private/util.ts
  packages/@aws-cdk/toolkit-lib/lib/api/tags/tags.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
  packages/aws-cdk/lib/api-private.ts
  packages/aws-cdk/lib/cli/cdk-toolkit.ts
Labels: pr/exempt-integ-test, p2

#582 chore(toolkit-lib): formatting and grammar changes in TSDoc comments
  packages/@aws-cdk/toolkit-lib/lib/actions/bootstrap/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/deploy/private/deploy-options.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/destroy/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/diff/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/drift/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/refactor/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/rollback/index.ts
  packages/@aws-cdk/toolkit-lib/lib/actions/watch/index.ts
  packages/@aws-cdk/toolkit-lib/lib/api/aws-auth/types.ts
  packages/@aws-cdk/toolkit-lib/lib/api/bootstrap/bootstrap-props.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/source-builder.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/deploy-stack.ts
  packages/@aws-cdk/toolkit-lib/lib/api/deployments/deployments.ts
  packages/@aws-cdk/toolkit-lib/lib/api/logs-monitor/logs-monitor.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/filter.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/notices.ts
  packages/@aws-cdk/toolkit-lib/lib/api/notices/web-data-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/stack-events/stack-activity-monitor.ts
  packages/@aws-cdk/toolkit-lib/lib/payloads/types.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/non-interactive-io-host.ts
  packages/@aws-cdk/toolkit-lib/lib/toolkit/toolkit.ts
Labels: pr/exempt-integ-test, p2

#584 chore: improved generation of stack definitions
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/cloudformation.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/execution.ts
  packages/@aws-cdk/toolkit-lib/lib/api/refactoring/stack-definitions.ts
  packages/@aws-cdk/toolkit-lib/test/api/refactoring/refactoring.test.ts
Labels: p2

#583 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#589 chore: update dependencies
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/.projen/deps.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  yarn.lock
Labels: p2

#591 chore(integ-testing): test CDK on multiple versions of Node
  .github/workflows/integ.yml
  .projenrc.ts
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#599 fix: pin minimatch to 10.0.1
  packages/@aws-cdk/toolkit-lib/package.json
  packages/aws-cdk/package.json
  yarn.lock
Labels: pr/exempt-integ-test, p1

#604 chore: run Amplify smoke tests only on Node 20
  .github/workflows/integ.yml
  projenrc/cdk-cli-integ-tests.ts
Labels: pr/exempt-integ-test, p2

#592 chore(toolkit-lib): include declaration maps so that API extractor can locate the source file
  .projenrc.ts
  packages/@aws-cdk/toolkit-lib/tsconfig.dev.json
  packages/@aws-cdk/toolkit-lib/tsconfig.dts.json
  packages/@aws-cdk/toolkit-lib/tsconfig.json
Labels: pr/exempt-integ-test, p2

#607 chore(node-bundle): produce a bundle metafile by default
  packages/@aws-cdk/integ-runner/.projen/tasks.json
  packages/@aws-cdk/node-bundle/src/api/bundle.ts
  packages/@aws-cdk/node-bundle/src/cli-main.ts
  packages/aws-cdk/.projen/tasks.json
  projenrc/bundle.ts
Labels: p2

#610 feat(cli): aws-cdk bundle is now targeting node18
  packages/@aws-cdk/node-bundle/src/api/bundle.ts
  packages/aws-cdk/README.md
Labels: p2

#613 chore: fix logs upload for Node smoke tests
  .github/workflows/integ.yml
  projenrc/cdk-cli-integ-tests.ts
Labels: pr/exempt-integ-test, p2

#615 chore(deps): upgrade dependencies
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/package.json
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#619 chore: slugify step must be run even if workflow is failing
  .github/workflows/integ.yml
  projenrc/cdk-cli-integ-tests.ts
Labels: p2

#620 chore: use isolatedModules tsconfig everywhere
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/jest.config.json
  packages/@aws-cdk-testing/cli-integ/tsconfig.dev.json
  packages/@aws-cdk-testing/cli-integ/tsconfig.json
  packages/@aws-cdk/cdk-cli-wrapper/jest.config.json
  packages/@aws-cdk/cdk-cli-wrapper/tsconfig.dev.json
  packages/@aws-cdk/cdk-cli-wrapper/tsconfig.json
  packages/@aws-cdk/cli-lib-alpha/jest.config.json
  packages/@aws-cdk/cli-lib-alpha/tsconfig.dev.json
  packages/@aws-cdk/cli-plugin-contract/jest.config.json
  packages/@aws-cdk/cli-plugin-contract/tsconfig.dev.json
  packages/@aws-cdk/cli-plugin-contract/tsconfig.json
  packages/@aws-cdk/cloud-assembly-schema/jest.config.json
  packages/@aws-cdk/cloud-assembly-schema/tsconfig.dev.json
  packages/@aws-cdk/cloudformation-diff/jest.config.json
  packages/@aws-cdk/cloudformation-diff/tsconfig.dev.json
  packages/@aws-cdk/cloudformation-diff/tsconfig.json
  packages/@aws-cdk/integ-runner/jest.config.json
  packages/@aws-cdk/integ-runner/tsconfig.dev.json
  packages/@aws-cdk/integ-runner/tsconfig.json
  packages/@aws-cdk/node-bundle/jest.config.json
  packages/@aws-cdk/node-bundle/tsconfig.dev.json
  packages/@aws-cdk/node-bundle/tsconfig.json
  packages/@aws-cdk/toolkit-lib/jest.config.json
  packages/@aws-cdk/user-input-gen/jest.config.json
  packages/@aws-cdk/user-input-gen/tsconfig.dev.json
  packages/@aws-cdk/user-input-gen/tsconfig.json
  packages/@aws-cdk/yarn-cling/jest.config.json
  packages/@aws-cdk/yarn-cling/tsconfig.dev.json
  packages/@aws-cdk/yarn-cling/tsconfig.json
  packages/aws-cdk/jest.config.json
  packages/aws-cdk/lib/api-private.ts
  packages/aws-cdk/lib/api/index.ts
  packages/aws-cdk/tsconfig.dev.json
  packages/aws-cdk/tsconfig.json
  packages/cdk-assets/jest.config.json
  packages/cdk-assets/tsconfig.dev.json
  packages/cdk-assets/tsconfig.json
  packages/cdk/jest.config.json
  packages/cdk/tsconfig.dev.json
  packages/cdk/tsconfig.json
Labels: p2

#630 fix: revert "retain type of context values and not convert them to string"
  packages/@aws-cdk-testing/cli-integ/resources/cdk-apps/app/app.js
  packages/aws-cdk/lib/cli/user-configuration.ts
  packages/aws-cdk/test/cli/configuration.test.ts
Labels: p2, bug

#611 feat(toolkit-lib): `fromAssemblyDirectory` can ignore missing context
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/context-aware-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/helpers.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/source-builder.ts
  packages/@aws-cdk/toolkit-lib/test/_fixtures/assembly-missing-context/cdk.out/assembly-Stage/StageStack130339B27.assets.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/assembly-missing-context/cdk.out/assembly-Stage/StageStack130339B27.template.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/assembly-missing-context/cdk.out/assembly-Stage/cdk.out
  packages/@aws-cdk/toolkit-lib/test/_fixtures/assembly-missing-context/cdk.out/assembly-Stage/manifest.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/assembly-missing-context/cdk.out/cdk.out
  packages/@aws-cdk/toolkit-lib/test/_fixtures/assembly-missing-context/cdk.out/manifest.json
  packages/@aws-cdk/toolkit-lib/test/_fixtures/assembly-missing-context/cdk.out/tree.json
  packages/@aws-cdk/toolkit-lib/test/api/cloud-assembly/source-builder.test.ts
Labels: p2

#612 docs: add .NET installation prerequisite to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: p2

#644 feat(integ-runner): support a new toolkit-lib based engine that does not require CDK CLI to be installed
  packages/@aws-cdk/cdk-cli-wrapper/lib/cdk-wrapper.ts
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/lib/cli.ts
  packages/@aws-cdk/integ-runner/lib/engines/toolkit-lib.ts
  packages/@aws-cdk/integ-runner/lib/runner/engine.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-suite.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/@aws-cdk/integ-runner/lib/runner/snapshot-test-runner.ts
  packages/@aws-cdk/integ-runner/lib/workers/common.ts
  packages/@aws-cdk/integ-runner/lib/workers/extract/extract_worker.ts
  packages/@aws-cdk/integ-runner/lib/workers/integ-watch-worker.ts
  packages/@aws-cdk/integ-runner/test/cli.test.ts
  packages/@aws-cdk/integ-runner/test/engines/toolkit-lib.test.ts
  packages/@aws-cdk/integ-runner/test/helpers.ts
  packages/@aws-cdk/integ-runner/test/runner/integ-test-runner.test.ts
  packages/@aws-cdk/integ-runner/test/runner/snapshot-test-runner.test.ts
Labels: p2

#623 fix(cli): logs entire environment
  packages/@aws-cdk/cli-lib-alpha/lib/cli.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/prepare-source.ts
  packages/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/source-builder.ts
  packages/aws-cdk/lib/cxapp/exec.ts
  packages/aws-cdk/test/cxapp/exec.test.ts
Labels: p2

#649 fix(integ-testing): proxy+notices test sometimes fails
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/proxy/cdk-requests-go-through-a-proxy-when-configured.integtest.ts
Labels: p2

#653 chore: remove node-bundle in favor of node-backpack
  .github/workflows/pull-request-lint.yml
  .projenrc.ts
  aws-cdk-cli.code-workspace
  package.json
  packages/@aws-cdk/cli-lib-alpha/.projen/tasks.json
  packages/@aws-cdk/integ-runner/.projen/deps.json
  packages/@aws-cdk/integ-runner/.projen/tasks.json
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/node-bundle/.eslintrc.js
  packages/@aws-cdk/node-bundle/.eslintrc.json
  packages/@aws-cdk/node-bundle/.gitattributes
  packages/@aws-cdk/node-bundle/.gitignore
  packages/@aws-cdk/node-bundle/.npmignore
  packages/@aws-cdk/node-bundle/.prettierignore
  packages/@aws-cdk/node-bundle/.prettierrc.json
  packages/@aws-cdk/node-bundle/.projen/deps.json
  packages/@aws-cdk/node-bundle/.projen/files.json
  packages/@aws-cdk/node-bundle/.projen/tasks.json
  packages/@aws-cdk/node-bundle/LICENSE
  packages/@aws-cdk/node-bundle/README.md
  packages/@aws-cdk/node-bundle/bin/node-bundle
  packages/@aws-cdk/node-bundle/jest.config.json
  packages/@aws-cdk/node-bundle/package.json
  packages/@aws-cdk/node-bundle/src/api/_attributions.ts
  packages/@aws-cdk/node-bundle/src/api/_shell.ts
  packages/@aws-cdk/node-bundle/src/api/bundle.ts
  packages/@aws-cdk/node-bundle/src/api/index.ts
  packages/@aws-cdk/node-bundle/src/api/violation.ts
  packages/@aws-cdk/node-bundle/src/cli-main.ts
  packages/@aws-cdk/node-bundle/src/cli.ts
  packages/@aws-cdk/node-bundle/src/index.ts
  packages/@aws-cdk/node-bundle/test/_package.ts
  packages/@aws-cdk/node-bundle/test/api/bundle.test.ts
  packages/@aws-cdk/node-bundle/test/cli.test.ts
  packages/@aws-cdk/node-bundle/tsconfig.dev.json
  packages/@aws-cdk/node-bundle/tsconfig.json
  packages/aws-cdk/.projen/deps.json
  packages/aws-cdk/.projen/tasks.json
  packages/aws-cdk/package.json
  packages/aws-cdk/test/tsconfig.json
  packages/aws-cdk/tsconfig.dev.json
  packages/aws-cdk/tsconfig.json
  projenrc/bundle.ts
  tsconfig.dev.json
  tsconfig.json
  yarn.lock
Labels: p2

#661 fix(cdk-assets): `docker-credential-cdk-assets` cannot be invoked as a program
  .projenrc.ts
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cdk-assets/cdk-assets-docker-credential.integtest.ts
  packages/cdk-assets/.projen/tasks.json
  packages/cdk-assets/bin/docker-credential-cdk-assets.ts
Labels: p2

#668 fix: unstable=toolkit-lib-engine has no effect
  packages/@aws-cdk/integ-runner/lib/workers/integ-test-worker.ts
Labels: p2

#669 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/upgrade.yml
  package.json
  packages/@aws-cdk-testing/cli-integ/package.json
  packages/@aws-cdk/cdk-assets-lib/lib/aws-types.ts
  packages/@aws-cdk/cdk-assets-lib/package.json
  packages/@aws-cdk/cdk-cli-wrapper/package.json
  packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
  packages/@aws-cdk/cli-lib-alpha/package.json
  packages/@aws-cdk/cli-plugin-contract/package.json
  packages/@aws-cdk/cloud-assembly-schema/package.json
  packages/@aws-cdk/cloudformation-diff/package.json
  packages/@aws-cdk/integ-runner/THIRD_PARTY_LICENSES
  packages/@aws-cdk/integ-runner/package.json
  packages/@aws-cdk/toolkit-lib/package.json
  packages/@aws-cdk/user-input-gen/package.json
  packages/@aws-cdk/yarn-cling/package.json
  packages/aws-cdk/THIRD_PARTY_LICENSES
  packages/aws-cdk/lib/init-templates/.init-version.json
  packages/aws-cdk/lib/init-templates/.recommended-feature-flags.json
  packages/aws-cdk/package.json
  packages/cdk-assets/THIRD_PARTY_LICENSES
  packages/cdk-assets/package.json
  packages/cdk/package.json
  yarn.lock
Labels: auto-approve, p2

#672 fix(cli-integ): CI=true test fails when jsii prints to stderr
  packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/ci-output/cdk-ci-true-output-to-stdout.integtest.ts
Labels: p2

#666 fix(integ-runner): integ-runner produces snapshot that doesn't validate
  packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts
  packages/@aws-cdk/integ-runner/lib/runner/runner-base.ts
  packages/@aws-cdk/integ-runner/test/runner/integ-test-runner.test.ts
Labels: p2
